ProjectTSB/TheSkyBlessing

.vscode/extensions.json, .vscode/settings.json
これが無いとmcfunctionファイルのコメントに色が付かなかったので…
=> おすすめ拡張機能にlanguage-mcfunctionを追加

Asset/data/asset/functions/sacred_treasure/0224.onegai_muscle_1/1.trigger.mcfunction, Asset/data/asset/functions/sacred_treasure/0224.onegai_muscle_1/2.check_condition.mcfunction, Asset/data/asset/functions/sacred_treasure/0224.onegai_muscle_1/3.main.mcfunction, Asset/data/asset/functions/sacred_treasure/0224.onegai_muscle_1/_.give.mcfunction, Asset/data/asset/tags/functions/sacred_treasure/click.carrot_on_a_stick.json
使用時体力を1にするためHealth-1のダメージを与えています
ScoreToHealthWrapperで Score→体力 ができるようになったらmain処理に変更を入れます
=> [神器0224] お願いマッスル[I類] の作成

Asset/data/asset/functions/sacred_treasure/0225.onegai_muscle_2/1.trigger.mcfunction, Asset/data/asset/functions/sacred_treasure/0225.onegai_muscle_2/2.check_condition.mcfunction, Asset/data/asset/functions/sacred_treasure/0225.onegai_muscle_2/3.main.mcfunction, Asset/data/asset/functions/sacred_treasure/0225.onegai_muscle_2/_.give.mcfunction, Asset/data/asset/tags/functions/sacred_treasure/click.carrot_on_a_stick.json
https://github.com/TheSkyBlock/TheSkyBlock/pull/69 と同上
=> [神器0225] お願いマッスル[II類] の作成

Asset/data/asset/functions/sacred_treasure/0227.onegai_muscle_4/1.trigger.mcfunction, Asset/data/asset/functions/sacred_treasure/0227.onegai_muscle_4/2.check_condition.mcfunction, Asset/data/asset/functions/sacred_treasure/0227.onegai_muscle_4/3.main.mcfunction, Asset/data/asset/functions/sacred_treasure/0227.onegai_muscle_4/_.give.mcfunction, Asset/data/asset/tags/functions/sacred_treasure/click.carrot_on_a_stick.json
=> [神器0227] お願いマッスル[IV類] の作成

Asset/data/asset/functions/sacred_treasure/0184.incresable_cookie/_.give.mcfunction
=> [神器0184]増えるクッキーの変更

Asset/data/asset/functions/sacred_treasure/0249.wakinyan/1.trigger.mcfunction, Asset/data/asset/functions/sacred_treasure/0249.wakinyan/2.check_condition.mcfunction, Asset/data/asset/functions/sacred_treasure/0249.wakinyan/3.main.mcfunction, Asset/data/asset/functions/sacred_treasure/0249.wakinyan/_.give.mcfunction, Asset/data/asset/tags/functions/sacred_treasure/attack/projectile.json
攻撃対象判定がまだあいまいです
lib:living,distance=..100にはしていますが、HurtTimeでしか識別していなかったりします
=> [神器0249] Wakinyanの作成

Asset/data/asset/functions/sacred_treasure/0250.phoenix/1.trigger.mcfunction, Asset/data/asset/functions/sacred_treasure/0250.phoenix/2.check_condition.mcfunction, Asset/data/asset/functions/sacred_treasure/0250.phoenix/3.main.mcfunction, Asset/data/asset/functions/sacred_treasure/0250.phoenix/_.give.mcfunction, Asset/data/asset/tags/functions/sacred_treasure/attack/projectile.json
=> [神器0250] Phoenixの作成

TheSkyBlock/data/core/functions/4_interval_tick.mcfunction, TheSkyBlock/data/core/functions/load.mcfunction, TheSkyBlock/data/core/functions/load_once.mcfunction, TheSkyBlock/data/core/functions/tick.mcfunction, TheSkyBlock/data/player_manager/functions/mp_viewer/_.index.d.mcfunction, TheSkyBlock/data/player_manager/functions/mp_viewer/_index.d.mcfunction, TheSkyBlock/data/player_manager/functions/mp_viewer/adjust_xpbar.mcfunction, TheSkyBlock/data/player_manager/functions/mp_viewer/check_xpbar.mcfunction
オバフロ二分探索はわからなかったので採用できませんでした・・・
datapack_versionが上がっています
=> MP表示を経験値barに移行

Asset/data/asset/functions/sacred_treasure/0204.spelunker_shoes/2.check_condition.mcfunction, TheSkyBlock/data/player_manager/functions/nbt_data/put.mcfunction
Spelunker Shoesで、通常ジャンプでも死亡するのが気になったので通常ジャンプでは死亡しないようにしたいな、と思いました
data get 時点でscaleを100に変更しています
FallDistanceScoreを利用していたspelunker shoesの2.condition_checkも変更しています
=> ScoreObjective:FallDistanceの仕様変更

Asset/data/asset/functions/sacred_treasure/0273.tonbo_gaeri/_.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0288.lamentation_sword/_.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0292.craving_sword/_.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0349.passion_pickaxe/_.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0364.red_knights_sword/_.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0382.haru_urara/_.give.mcfunction
=> 各神器のAttributeをリファクタリング

Asset/data/asset/functions/sacred_treasure/0106.stone_cutter_blade/_.give.mcfunction
=> [神器106]イシキリブレードを石切台から棒へ

Asset/data/asset/functions/sacred_treasure/0454.kinoko/3.main.mcfunction
=> [神器0454] きのこの方が優位であることを効果にて証明

TheSkyBlock/data/core/functions/tick.mcfunction, TheSkyBlock/data/player_manager/functions/adjust_hunger/_index.d.mcfunction, TheSkyBlock/data/player_manager/functions/adjust_hunger/observe.mcfunction, TheSkyBlock/data/player_manager/functions/adjust_hunger/respawn.delay.mcfunction
=> player_manager:adjust_hunger/observeをschedule実行に

Asset/data/asset/functions/sacred_treasure/0077.swords_of_waterfall_climbing/3.1.effectclear.mcfunction, Asset/data/asset/functions/sacred_treasure/0077.swords_of_waterfall_climbing/3.3.falldistance.mcfunction, Asset/data/asset/functions/sacred_treasure/0077.swords_of_waterfall_climbing/_index.d.mcfunction, Asset/data/asset/functions/sacred_treasure/0204.spelunker_shoes/2.check_condition.mcfunction
=> 落下距離を使う神器の修正

Asset/data/asset/functions/sacred_treasure/0297.spirit_world_trance/3.2.reset.mcfunction, Asset/data/asset/functions/sacred_treasure/0297.spirit_world_trance/3.main.mcfunction, Asset/data/asset/functions/sacred_treasure/0297.spirit_world_trance/_index.d.mcfunction
ついでにAECに時間制限も付与
効果時間内に帰ってこなかった場合死んでもらいます
=> [神器297修正]転移に失敗した時そのままなことを修正

Asset/data/asset/tags/functions/sacred_treasure/attack/melee.json
=> [修正]神器meleeトリガーに抜けがあったのを修正

Asset/data/asset/functions/mob/0186.ferocious_bee/attack/1.trigger.mcfunction, Asset/data/asset/functions/mob/0186.ferocious_bee/attack/2.attack.mcfunction, Asset/data/asset/functions/mob/0186.ferocious_bee/death/1.trigger.mcfunction, Asset/data/asset/functions/mob/0186.ferocious_bee/death/2.death.mcfunction, Asset/data/asset/functions/mob/0186.ferocious_bee/hurt/1.trigger.mcfunction, Asset/data/asset/functions/mob/0186.ferocious_bee/hurt/2.hurt.mcfunction, Asset/data/asset/functions/mob/0186.ferocious_bee/summon/1.trigger.mcfunction, Asset/data/asset/functions/mob/0186.ferocious_bee/summon/2.summon.mcfunction, Asset/data/asset/loot_tables/mob/death/0186.ferocious_bee.json, Asset/data/asset/tags/functions/mob/attack.json, Asset/data/asset/tags/functions/mob/death.json, Asset/data/asset/tags/functions/mob/hurt.json, Asset/data/asset/tags/functions/mob/summon.json
=> ✨ [MOB0186] 凶暴なハチを作成

TheSkyBlock/data/api/functions/player_modifier/attack/base/get.mcfunction, TheSkyBlock/data/api/functions/player_modifier/attack/fire/get.mcfunction, TheSkyBlock/data/api/functions/player_modifier/attack/magic/get.mcfunction, TheSkyBlock/data/api/functions/player_modifier/attack/physical/get.mcfunction, TheSkyBlock/data/api/functions/player_modifier/attack/thunder/get.mcfunction, TheSkyBlock/data/api/functions/player_modifier/attack/water/get.mcfunction, TheSkyBlock/data/api/functions/player_modifier/defense/base/get.mcfunction, TheSkyBlock/data/api/functions/player_modifier/defense/fire/get.mcfunction, TheSkyBlock/data/api/functions/player_modifier/defense/magic/get.mcfunction, TheSkyBlock/data/api/functions/player_modifier/defense/physical/get.mcfunction, TheSkyBlock/data/api/functions/player_modifier/defense/thunder/get.mcfunction, TheSkyBlock/data/api/functions/player_modifier/defense/water/get.mcfunction, TheSkyBlock/data/api/functions/player_modifier/heal/get.mcfunction, TheSkyBlock/data/api/functions/player_modifier/mp_regen/get.mcfunction
=> ✨ プレイヤーの補正情報を取得できるAPIを作成

Asset/data/asset/functions/sacred_treasure/0610.call_fish/rejoin_process.mcfunction, Asset/data/asset/functions/sacred_treasure/0610.call_fish/trigger/3.1.tick.mcfunction, Asset/data/asset/functions/sacred_treasure/0610.call_fish/trigger/_index.d.mcfunction, Asset/data/asset/functions/sacred_treasure/0745.blade_of_whirlwind/trigger/5.knockback.mcfunction, Asset/data/asset/tags/functions/rejoin.json
=> 🩹 神器の細かい修正

TheSkyBlock/data/core/functions/load.mcfunction, TheSkyBlock/data/core/functions/load_once.mcfunction, TheSkyBlock/data/lib/functions/message/god/flora/mercy.mcfunction, TheSkyBlock/data/lib/functions/message/god/nyaptov/mercy.mcfunction, TheSkyBlock/data/lib/functions/message/god/rumor/mercy.mcfunction, TheSkyBlock/data/lib/functions/message/god/urban/mercy.mcfunction, TheSkyBlock/data/lib/functions/message/god/wi-ki/mercy.mcfunction, TheSkyBlock/data/player_manager/functions/god/_index.d.mcfunction, TheSkyBlock/data/player_manager/functions/god/flora/in_temple.mcfunction, TheSkyBlock/data/player_manager/functions/god/mercy/.mcfunction, TheSkyBlock/data/player_manager/functions/god/mercy/listener.mcfunction, TheSkyBlock/data/player_manager/functions/god/mercy/mercy.mcfunction, TheSkyBlock/data/player_manager/functions/god/mercy/offering/get.mcfunction, TheSkyBlock/data/player_manager/functions/god/mercy/offering/init.mcfunction, TheSkyBlock/data/player_manager/functions/god/mercy/offering/send_require_message.mcfunction, TheSkyBlock/data/player_manager/functions/god/mercy/offering/set_next.mcfunction, TheSkyBlock/data/player_manager/functions/god/mercy/on_click.mcfunction, TheSkyBlock/data/player_manager/functions/god/mercy/on_mercy.mcfunction, TheSkyBlock/data/player_manager/functions/god/nyaptov/in_temple.mcfunction, TheSkyBlock/data/player_manager/functions/god/rumor/in_temple.mcfunction, TheSkyBlock/data/player_manager/functions/god/urban/in_temple.mcfunction, TheSkyBlock/data/player_manager/functions/god/wi-ki/in_temple.mcfunction
=> ✨ 慈悲を乞った際の処理を作成

TheSkyBlock/data/common/loot_tables/sacred_shard_lv-1.json, TheSkyBlock/data/common/loot_tables/sacred_shard_lv-2.json, TheSkyBlock/data/common/loot_tables/sacred_shard_lv-3.json, TheSkyBlock/data/common/loot_tables/sacred_shard_lv-4.json
=> ✨ シャードのアイテムを作成

TheSkyBlock/data/minecraft/loot_tables/blocks/lime_shulker_box.json
=> 🩹 shulker_boxのルートテーブルが1.18でも動作するように

TheSkyBlock/data/common/loot_tables/sacred_shard/lv-1.json, TheSkyBlock/data/common/loot_tables/sacred_shard/lv-2.json, TheSkyBlock/data/common/loot_tables/sacred_shard/lv-3.json, TheSkyBlock/data/common/loot_tables/sacred_shard/lv-4.json, TheSkyBlock/data/core/functions/load.mcfunction, TheSkyBlock/data/core/functions/load_once.mcfunction, TheSkyBlock/data/world_manager/functions/area/02-01.shard_processor.mcfunction, TheSkyBlock/data/world_manager/functions/area/02.islands/on_tick.mcfunction, TheSkyBlock/data/world_manager/functions/gimmick/_index.d.mcfunction, TheSkyBlock/data/world_manager/functions/gimmick/shard_processor/.mcfunction, TheSkyBlock/data/world_manager/functions/gimmick/shard_processor/check_item/.mcfunction, TheSkyBlock/data/world_manager/functions/gimmick/shard_processor/check_item/invalid.mcfunction, TheSkyBlock/data/world_manager/functions/gimmick/shard_processor/process/.mcfunction, TheSkyBlock/data/world_manager/functions/gimmick/shard_processor/process/complete.mcfunction, TheSkyBlock/data/world_manager/functions/gimmick/shard_processor/process/model_modifier.mcfunction, TheSkyBlock/data/world_manager/predicates/area/02-01.shard_processor.json
=> ✨ シャード加工システムを作成

TheSkyBlock/data/player_manager/functions/god/mercy/offering/init.mcfunction
=> 🐛 慈悲を乞う際のメッセージのミスを修正

TheSkyBlock/data/player_manager/functions/god/mercy/offering/send_require_message.mcfunction
=> 🐛 慈悲を乞うのメッセージが全体に表示されるのを修正

TheSkyBlock/data/core/functions/load_once.mcfunction, TheSkyBlock/data/core/functions/migration/v0.0.1/.mcfunction, TheSkyBlock/data/player_manager/functions/god/change_believe/check-1/.mcfunction, TheSkyBlock/data/player_manager/functions/god/change_believe/check-1/on_click.mcfunction, TheSkyBlock/data/player_manager/functions/god/change_believe/check-2/.mcfunction, TheSkyBlock/data/player_manager/functions/god/mercy/.mcfunction, TheSkyBlock/data/player_manager/functions/god/mercy/listener.mcfunction, TheSkyBlock/data/player_manager/functions/god/mercy/on_check_offering.mcfunction, TheSkyBlock/data/player_manager/functions/god/mercy/on_click.mcfunction
=> 🐛 信仰周りのチャットが動作しないことがあるのを修正

TheSkyBlock/data/api/functions/player_modifier/core/defense/base/remove.mcfunction, TheSkyBlock/data/api/functions/player_modifier/core/defense/fire/remove.mcfunction, TheSkyBlock/data/api/functions/player_modifier/core/defense/magic/remove.mcfunction, TheSkyBlock/data/api/functions/player_modifier/core/defense/physical/remove.mcfunction, TheSkyBlock/data/api/functions/player_modifier/core/defense/thunder/remove.mcfunction, TheSkyBlock/data/api/functions/player_modifier/core/defense/water/remove.mcfunction
=> 🐛 ModifierAPIのdefense/*/getのAmountが反転しているのを修正

TheSkyBlock/data/asset_manager/functions/mob/summon/set_tag.mcfunction
=> 🐛 天使がデスポーンしないように

TheSkyBlock/data/asset_manager/functions/spawner/spawn/.mcfunction, TheSkyBlock/data/asset_manager/functions/spawner/spawn/nearby_entities/get.mcfunction, TheSkyBlock/data/asset_manager/functions/spawner/spawn/nearby_entities/get_from_selector/.mcfunction, TheSkyBlock/data/asset_manager/functions/spawner/spawn/nearby_entities/try_get_from_cache/.mcfunction
=> 🐛 スポナーのスポーン数上限が正常に動作しないのを修正

Asset/data/asset/functions/mob/0021.demon_eye/tick/2.tick.mcfunction, Asset/data/asset/functions/mob/0023.chainsaw_zombie/tick/2.1.attack.mcfunction, Asset/data/asset/functions/mob/0047.the_heretic/attack/2.1.first_attack.mcfunction, Asset/data/asset/functions/mob/0053.executioners/attack/2.attack.mcfunction, Asset/data/asset/functions/mob/0053.executioners/hurt/2.1.backstep.mcfunction, Asset/data/asset/functions/mob/0104.mad_scientist/hurt/3.teleport.mcfunction, Asset/data/asset/functions/mob/0104.mad_scientist/tick/4.throw_potion.mcfunction, Asset/data/asset/functions/mob/0124.skull_harpy/hurt/2.hurt.mcfunction, Asset/data/asset/functions/mob/0124.skull_harpy/tick/2.1.motion.mcfunction, Asset/data/asset/functions/mob/0182.skull_raven/hurt/2.hurt.mcfunction, Asset/data/asset/functions/mob/0182.skull_raven/tick/3.motion.mcfunction, Asset/data/asset/functions/sacred_treasure/0107.dispenser_canon/trigger/3.main.mcfunction, Asset/data/asset/functions/sacred_treasure/0559.solitariness/trigger/3.main.mcfunction, Asset/data/asset/functions/sacred_treasure/0745.blade_of_whirlwind/trigger/3.main.mcfunction, Asset/data/asset/functions/sacred_treasure/0745.blade_of_whirlwind/trigger/5.knockback.mcfunction, Asset/data/asset/functions/sacred_treasure/0745.blade_of_whirlwind/trigger/6.knockback_resist.mcfunction, TheSkyBlock/data/lib/functions/motion/.mcfunction, TheSkyBlock/data/lib/functions/motion/core/apply.mcfunction, TheSkyBlock/data/lib/functions/motion/core/knockback_resistance.mcfunction, TheSkyBlock/data/lib/functions/motion/core/reset.mcfunction
data modify storage lib: Argument.KnockbackResist set value true
上記のコマンドを実行前に入れることでノックバックを計算した上でmotionを与えることができる
=> ✨ Motionlibにノックバック耐性考慮を追加

TheSkyBlock/data/asset_manager/functions/sacred_treasure/data/pre_event_put/new.mcfunction, TheSkyBlock/data/asset_manager/functions/sacred_treasure/data/pre_event_put/old.mcfunction, TheSkyBlock/data/asset_manager/functions/sacred_treasure/data/reset_context.mcfunction, TheSkyBlock/data/asset_manager/functions/sacred_treasure/triggers/check_change_armor/check.mcfunction, TheSkyBlock/data/asset_manager/functions/sacred_treasure/triggers/dis_equip.mcfunction, TheSkyBlock/data/asset_manager/functions/sacred_treasure/triggers/equip.mcfunction
=> 🐛 トリガーが一定の条件下で動作しないのを修正

TheSkyBlock/data/asset_manager/functions/sacred_treasure/check/check_and_store_local_cooldown.mcfunction
=> 🐛 クールダウン表示の更新条件を修正

TheSkyBlock/data/world_manager/functions/gimmick/shard_processor/.mcfunction
=> 🐛 シャード加工機の額縁を破壊するとモデルが増殖するのを修正

Asset/data/asset/functions/sacred_treasure/0152.call_cat/trigger/3.1.2.goodbye_cat.mcfunction
=> 🩹 [神器0152] 猫が去るときの座標を修正

TheSkyBlock/data/core/functions/handler/flying_elytra.mcfunction, TheSkyBlock/data/core/functions/load_once.mcfunction, TheSkyBlock/data/core/functions/tick/player.mcfunction, TheSkyBlock/data/core/functions/tick/post-tick-proc_player.mcfunction, TheSkyBlock/data/player_manager/functions/god/_index.d.mcfunction, TheSkyBlock/data/player_manager/functions/god/nyaptov/passive.mcfunction
=> 🚸 エリトラ飛行中は信仰による落下速度低下の恩恵を受けないように

.vscode/settings.json
=> :technologist: 各種テンプレートを更新

Asset/data/asset/functions/sacred_treasure/0002.blessing/give/get_random_name.mcfunction, TheSkyBlock/data/api/functions/inventory/clear.mcfunction, TheSkyBlock/data/asset_manager/functions/sacred_treasure/give.mcfunction, TheSkyBlock/data/asset_manager/functions/trader/register/set_data.mcfunction, TheSkyBlock/data/lib/functions/array/core/force_delete_cache.mcfunction, TheSkyBlock/data/lib/functions/array/core/reverse.mcfunction, TheSkyBlock/data/lib/functions/array/core/shuffle.mcfunction, TheSkyBlock/data/lib/functions/array/force_delete_cache.mcfunction, TheSkyBlock/data/lib/functions/array/move.mcfunction, TheSkyBlock/data/lib/functions/array/packing_chest.mcfunction, TheSkyBlock/data/lib/functions/array/picks.mcfunction, TheSkyBlock/data/lib/functions/array/reverse.mcfunction, TheSkyBlock/data/lib/functions/array/revert.mcfunction, TheSkyBlock/data/lib/functions/array/session/close.mcfunction, TheSkyBlock/data/lib/functions/array/session/open.mcfunction, TheSkyBlock/data/lib/functions/array/shuffle.mcfunction, TheSkyBlock/data/lib/functions/array/sort_ascend.mcfunction, TheSkyBlock/data/lib/functions/array/sort_descend.mcfunction, TheSkyBlock/data/lib/functions/bit_array_to_integer/core/main.mcfunction, TheSkyBlock/data/lib/functions/bit_array_to_integer/core/recursive.mcfunction, TheSkyBlock/data/player_manager/functions/god/mercy/offering/set_next.mcfunction, TheSkyBlock/data/player_manager/functions/lost_item/drop/.mcfunction, TheSkyBlock/data/player_manager/functions/lost_item/give_all/packing.user.mcfunction, TheSkyBlock/data/player_manager/functions/lost_item/give_part/.mcfunction
=> 🧑‍💻 lib:array/の利用を厳格にする

Asset/data/asset/functions/mob/0022.red_knight/remove/1.trigger.mcfunction, Asset/data/asset/functions/mob/0131.haruclaire/remove/1.trigger.mcfunction, Asset/data/asset/functions/mob/0175.queen_bee/remove/1.trigger.mcfunction
=> remove処理のIDが違うのを修正

TheSkyBlessing/data/core/functions/load_once.mcfunction
=> :fire: datapackの処理順序設定を削除

TheSkyBlessing/data/core/functions/load_once.mcfunction, TheSkyBlessing/data/core/functions/migration/.mcfunction, TheSkyBlessing/data/core/functions/migration/v0.0.4/.mcfunction
=> ✨ v0.0.4マイグレーション

Asset/data/asset/functions/mob/0244.ignition_spider/attack/1.trigger.mcfunction, Asset/data/asset/functions/mob/0244.ignition_spider/attack/2.attack.mcfunction, Asset/data/asset/functions/mob/0244.ignition_spider/death/1.trigger.mcfunction, Asset/data/asset/functions/mob/0244.ignition_spider/death/2.death.mcfunction, Asset/data/asset/functions/mob/0244.ignition_spider/summon/1.trigger.mcfunction, Asset/data/asset/functions/mob/0244.ignition_spider/summon/2.summon.mcfunction, Asset/data/asset/functions/mob/0244.ignition_spider/tick/1.trigger.mcfunction, Asset/data/asset/functions/mob/0244.ignition_spider/tick/2.tick.mcfunction, Asset/data/asset/loot_tables/mob/death/0244.ignition_spider.json, Asset/data/asset/tags/functions/mob/attack.json, Asset/data/asset/tags/functions/mob/death.json, Asset/data/asset/tags/functions/mob/summon.json, Asset/data/asset/tags/functions/mob/tick.json
当たると燃えるただのlv1スパイダー
ウィキ使うの好きなのに試練をもたらす自分
=> ✨ [MOB0244] イグニッションスパイダーを作成

Asset/data/asset/functions/sacred_treasure/0012.sketchy_herb/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0043.fruit_of_wisdom/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0105.secret_meat/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0185.increased_cookie/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0217.fish/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0245.skewered_meat/give/2.give.mcfunction
=> 🐛 使用回数の設定されていない食料系神器を修正

Asset/data/asset/functions/sacred_treasure/0079.shoot_down_a_flying_dragon/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0079.shoot_down_a_flying_dragon/trigger/3.main.mcfunction
改めてみるとまだfunction実行コスト下げられることに気が付きました
範囲攻撃の条件がわかりにくすぎたので修正しました
=> 🚸 [神器0079] 細かい修正

TheSkyBlessing/data/player_manager/functions/god/mercy/mercy.mcfunction, TheSkyBlessing/data/player_manager/functions/god/mercy/offering/get.mcfunction, TheSkyBlessing/data/player_manager/functions/god/mercy/offering/send_require_message.mcfunction, TheSkyBlessing/data/player_manager/functions/god/mercy/on_click.mcfunction, TheSkyBlessing/data/player_manager/functions/god/mercy/on_mercy/check.mcfunction, TheSkyBlessing/data/player_manager/functions/god/mercy/on_mercy/pre.mcfunction
=> 🐛 失ったアイテムがない状態でも慈悲を乞うことができるのを修正

TheSkyBlessing/data/asset_manager/functions/island/dispel/.mcfunction
Fix #777
幸運っぽい番号のissueはもやんが原因でした！！！！****！！！！！！！
=> :bug: 動いていなくとも解呪がキャンセルされることがあるのを修正

.vscode/settings.json
"question": "MobID"→"question": "MobのID"に寄せた
=> 🩹 テンプレートの質問内容が異なっているのを修正

.vscode/settings.json, TheSkyBlessing/data/lib/functions/array/compare.mcfunction, TheSkyBlessing/data/lib/functions/array/core/compare.mcfunction, TheSkyBlessing/data/lib/functions/array/session/close.mcfunction, TheSkyBlessing/data/lib/functions/array/session/open.mcfunction
=> 🩹 lib:array/compareの修正

TheSkyBlessing/data/lib/functions/array/compare.mcfunction
=> :adhesive_bandage: lib:array/compareの変更忘れを修正

TheSkyBlessing/data/lib/functions/array/_index.d.mcfunction, TheSkyBlessing/data/lib/functions/array/compare.mcfunction, TheSkyBlessing/data/lib/functions/array/compare_single.mcfunction, TheSkyBlessing/data/lib/functions/array/core/compare_single.mcfunction, TheSkyBlessing/data/lib/functions/array/core/mask.mcfunction, TheSkyBlessing/data/lib/functions/array/mask.mcfunction
ついでにlib:array/compareのIMP-Docもきれいにした
=> 🧑‍💻 lib:array/にmask, compare_singleを追加

Asset/data/asset/functions/sacred_treasure/0262.angel_ray_lv.1/trigger/effect/.mcfunction, Asset/data/asset/functions/sacred_treasure/0266.angel_ray_lv.5/trigger/effect/.mcfunction, Asset/data/asset/functions/sacred_treasure/0270.angel_ray_lv.10/trigger/effect/.mcfunction, Asset/data/asset/functions/sacred_treasure/0355.barrel/trigger/3.main.mcfunction, TheSkyBlessing/data/core/functions/handler/first_join.mcfunction, TheSkyBlessing/data/player_manager/functions/god/rumor/passive/.mcfunction
これに合わせてAngelRayのバグが**偶然**修正されています
=> 💥 Friendタグをプレイヤーにつけるように

TheSkyBlessing/data/core/functions/handler/death.mcfunction, TheSkyBlessing/data/core/functions/tick/player.mcfunction
=> 🐛 死亡メッセージが二重に出力されるのを修正

Asset/data/asset/functions/sacred_treasure/0454.kinoko/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0454.kinoko/trigger/3.main.mcfunction, Asset/data/asset/functions/sacred_treasure/0455.takenoko/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0455.takenoko/trigger/3.main.mcfunction
実在の商品に対して多少とはいえマイナスのイメージを付ける方がよろしくないと思いました
=> 🩹 [神器0454,0455] 不適切な表現を修正

TheSkyBlessing/data/core/functions/tick/.mcfunction, TheSkyBlessing/data/core/functions/tick/check_item_meta/_index.mcfunction, TheSkyBlessing/data/core/functions/tick/check_item_meta/entity.mcfunction
=> :zap: ItemMetaDataのチェックを一度しか行わないように

TheSkyBlessing/data/asset_manager/functions/sacred_treasure/data/current/update/when_modified/hotbar.mcfunction
=> :fire: 不要なコマンドを削除

Asset/data/asset/functions/sacred_treasure/0005.musket_matchlock/give/2.give.mcfunction
=> 要求アイテムの誤字を修正

Asset/data/asset/functions/sacred_treasure/0930.z_flag/give/1.trigger.mcfunction, Asset/data/asset/functions/sacred_treasure/0930.z_flag/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0930.z_flag/register.mcfunction, Asset/data/asset/functions/sacred_treasure/0930.z_flag/trigger/1.trigger.mcfunction, Asset/data/asset/functions/sacred_treasure/0930.z_flag/trigger/2.check_condition.mcfunction, Asset/data/asset/functions/sacred_treasure/0930.z_flag/trigger/3.main.mcfunction, Asset/data/asset/functions/sacred_treasure/0930.z_flag/trigger/_index.d.mcfunction, Asset/data/asset/functions/sacred_treasure/0930.z_flag/trigger/dis_equip/.mcfunction, Asset/data/asset/functions/sacred_treasure/0930.z_flag/trigger/dis_equip/main.mcfunction, Asset/data/asset/tags/functions/sacred_treasure/dis_equip.json, Asset/data/asset/tags/functions/sacred_treasure/equip.json, Asset/data/asset/tags/functions/sacred_treasure/give.json, Asset/data/asset/tags/functions/sacred_treasure/register.json
=> ✨ [神器0930] Z旗を作成

.vscode/settings.json
=> 🧑‍💻 hotbar神器用のテンプレートを追加

TheSkyBlessing/data/core/functions/tick/.mcfunction, TheSkyBlessing/data/player_manager/functions/manage_tag/.mcfunction, TheSkyBlessing/data/player_manager/functions/manage_tag/_index.d.mcfunction
=> :technologist: PlayerShouldInvulnerableタグを作成

TheSkyBlessing/data/lib/functions/heal/core/non-player.mcfunction
少数第3-4桁を無視するようになったのはまぁいいでしょ
Fix #846
=> :bug: lib:heal/でモブが最大体力以上に回復できるのを修正

Asset/data/asset/functions/sacred_treasure/0961.light_charm/give/1.trigger.mcfunction, Asset/data/asset/functions/sacred_treasure/0961.light_charm/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0961.light_charm/trigger/1.trigger.mcfunction, Asset/data/asset/functions/sacred_treasure/0961.light_charm/trigger/2.check_condition.mcfunction, Asset/data/asset/functions/sacred_treasure/0961.light_charm/trigger/3.main.mcfunction, Asset/data/asset/functions/sacred_treasure/0961.light_charm/trigger/add_modifier.mcfunction, Asset/data/asset/functions/sacred_treasure/0961.light_charm/trigger/dis_equip/.mcfunction, Asset/data/asset/functions/sacred_treasure/0961.light_charm/trigger/dis_equip/main.mcfunction, Asset/data/asset/tags/functions/sacred_treasure/dis_equip.json, Asset/data/asset/tags/functions/sacred_treasure/equip.json, Asset/data/asset/tags/functions/sacred_treasure/give.json
=> ✨ [神器0961] 軽装のチャームを作成

TheSkyBlessing/data/asset_manager/functions/sacred_treasure/_index.d.mcfunction, TheSkyBlessing/data/lib/functions/damage/.mcfunction, TheSkyBlessing/data/lib/functions/damage/_index.d.mcfunction, TheSkyBlessing/data/lib/functions/damage/core/health_subtract/.mcfunction, TheSkyBlessing/data/lib/functions/damage/core/health_subtract/player.mcfunction, TheSkyBlessing/data/lib/functions/damage/core/trigger_on_damage/.mcfunction, TheSkyBlessing/data/lib/functions/damage/core/trigger_on_damage/as_attacker.mcfunction, TheSkyBlessing/data/mob_manager/functions/_index.d.mcfunction, TheSkyBlessing/data/mob_manager/functions/entity_finder/attacking_entity/_index.d.mcfunction, TheSkyBlessing/data/mob_manager/functions/entity_finder/attacking_entity/on_hurt.mcfunction
=> :bug: lib:damage/がon_damage/from_entityを発火しないのを修正

TheSkyBlessing/data/asset_manager/functions/mob/summon/set_data.mcfunction, TheSkyBlessing/data/core/functions/load_once.mcfunction, TheSkyBlessing/data/mob_manager/functions/init/.mcfunction, TheSkyBlessing/data/mob_manager/functions/init/modify_health.mcfunction, TheSkyBlessing/data/mob_manager/functions/init/multiplay_multiplier/angel.mcfunction, TheSkyBlessing/data/mob_manager/functions/init/multiplay_multiplier/normal.mcfunction
=> :children_crossing: Mobの体力にマルチ補正をかける

TheSkyBlessing/data/api/functions/mob/get_max_health_multiplier.mcfunction, TheSkyBlessing/data/core/functions/load_once.mcfunction, TheSkyBlessing/data/lib/functions/heal/.mcfunction, TheSkyBlessing/data/lib/functions/heal/core/non-player.mcfunction, TheSkyBlessing/data/lib/functions/heal/reset.mcfunction, TheSkyBlessing/data/mob_manager/functions/init/multiplay_multiplier/angel.mcfunction, TheSkyBlessing/data/mob_manager/functions/init/multiplay_multiplier/normal.mcfunction
それに伴ってapiが増えてたりしますがまぁこれくらいは許容して(
=> 🧑‍💻 lib:heal/に最大体力補正がかかるように

Asset/data/asset/functions/mob/0287.burning_stomper/tick/2.tick.mcfunction
=> 🩹 [MOB0287] バーニングストンパーのスコアリセット条件を変更

Asset/data/asset/functions/sacred_treasure/0515.time_medicine/give/1.trigger.mcfunction, Asset/data/asset/functions/sacred_treasure/0515.time_medicine/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0515.time_medicine/trigger/1.trigger.mcfunction, Asset/data/asset/functions/sacred_treasure/0515.time_medicine/trigger/2.check_condition.mcfunction, Asset/data/asset/functions/sacred_treasure/0515.time_medicine/trigger/3.main.mcfunction, Asset/data/asset/functions/sacred_treasure/0515.time_medicine/trigger/day.mcfunction, Asset/data/asset/functions/sacred_treasure/0515.time_medicine/trigger/night.mcfunction, Asset/data/asset/tags/functions/sacred_treasure/give.json, Asset/data/asset/tags/functions/sacred_treasure/use_item.json
=> ✨ [神器0515] 時刻みのポーションを作成

TheSkyBlessing/data/core/functions/load_once.mcfunction, TheSkyBlessing/data/core/functions/tick/player/pre.mcfunction, TheSkyBlessing/data/lib/predicates/is_player_moving.json, TheSkyBlessing/data/player_manager/functions/pos_diff.mcfunction
=> :technologist: lib:is_player_moving predicateを作成する

Asset/data/asset/functions/mob/1004.tultaria/0.load.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/_index.d.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/death/2.death.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/death/3.death_tick.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/death/4.main.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/death/explosion.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/death/explosion_final.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/rejoin_process.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/summon/2.summon.mcfunction
・ドカンドカンと爆発しまくります。前よりかは派手だし、倒した感があるはず。
・相変わらず仮置きではあります。
=> 🚸 ラスボスの新しい撃破演出を作成

Asset/data/asset/functions/sacred_treasure/0002.blessing/trigger/3.main.mcfunction
This reverts commit 92d769eb7a89d33ffa3c73e590d0c652d96143fd.
=> :rewind: Revert ":children_crossing: MP増加量を調整"

Asset/data/asset/functions/sacred_treasure/0001.book_of_all-seeing/give/2.give.mcfunction
・「ダメージの通りやすさ」と明言することにした。
・表示時の[+++++]がどっちに有利なのか分からないっていうから…
=> 🚸 [神器0001] アイテムの説明をちょっと変更

TheSkyBlessing/data/asset_manager/functions/mob/_index.d.mcfunction, TheSkyBlessing/data/asset_manager/functions/mob/bossbar/init.mcfunction, TheSkyBlessing/data/asset_manager/functions/mob/bossbar/reset.mcfunction, TheSkyBlessing/data/asset_manager/functions/mob/bossbar/tick.mcfunction, TheSkyBlessing/data/asset_manager/functions/mob/common_tag/.mcfunction, TheSkyBlessing/data/asset_manager/functions/mob/summon/set_data.mcfunction, TheSkyBlessing/data/asset_manager/functions/mob/tick/.mcfunction, TheSkyBlessing/data/asset_manager/functions/mob/tick/global.mcfunction, TheSkyBlessing/data/asset_manager/functions/mob/triggers/.mcfunction, TheSkyBlessing/data/core/functions/load_once.mcfunction, TheSkyBlessing/data/core/functions/tick/.mcfunction
=> :sparkles: ボスバーを作成

Asset/data/asset/tags/functions/sacred_treasure/register.json
=> 🩹 神器0976の登録処理が抜けていたのを修正

TheSkyBlessing/data/asset_manager/functions/island/dispel/.mcfunction, TheSkyBlessing/data/asset_manager/functions/island/dispel/successful.mcfunction
=> :ambulance: 解呪時のテレポーター起動処理が正常に動作してないのを修正

Asset/data/asset/functions/sacred_treasure/0246.magical_cane/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0246.magical_cane/trigger/3.2.strong_hit.mcfunction, Asset/data/asset/functions/sacred_treasure/0246.magical_cane/trigger/3.3.hyper_hit.mcfunction, Asset/data/asset/functions/sacred_treasure/0246.magical_cane/trigger/3.main.mcfunction
・ダメージが10倍！
・5回使える！
・グローバルクールついた！
・クールタイムもついた！
=> 🚸 [神器0246] マジカルステッキがいい感じに

TheSkyBlessing/data/world_manager/functions/gimmick/.mcfunction, TheSkyBlessing/data/world_manager/functions/gimmick/return_to_overworld_portal/_index.d.mcfunction, TheSkyBlessing/data/world_manager/functions/gimmick/return_to_overworld_portal/main.mcfunction, TheSkyBlessing/data/world_manager/functions/gimmick/return_to_overworld_portal/return_to_overworld.mcfunction, TheSkyBlessing/data/world_manager/functions/gimmick/return_to_overworld_portal/tick.mcfunction
=> ✨ エンドから地上に帰るポータルを設置

Asset/data/asset/functions/mob/0182.skull_raven/attack/2.attack.mcfunction, Asset/data/asset/functions/mob/0182.skull_raven/summon/2.summon.mcfunction
矢の打ち上げ効果削除、HP低下。
なんか…コイツだけTUSBしてるような…
=> 🚸 [MOB0182] スカルレイブンを弱体化

TheSkyBlessing/data/world_manager/functions/gimmick/return_to_overworld_portal/return_to_overworld.mcfunction
冷静に考えてみれば、作った後一度も動作チェックしてませんでした。同じコマンドだしと完全に油断していました
=> エンドから地上への帰還ポータルが全く機能していないのを修正

.vscode/settings.json
⚖️
ずっとバランス調整を🚸で入れてたんですがかなり微妙な気持ちだったのでこの際追加してしまおうって話
=> :wrench: gitmojiにバランス調整に関する絵文字を追加する

Asset/data/asset/functions/mob/0204_infernal_watcher/summon/2.summon.mcfunction
これまた私のミスで、TypeがEnemyではなくzombieになっていました。TypeってそのTypeじゃない。
=> 🐛 [MOB0204] ヘルズウォッチャーのTypeを修正

Asset/data/asset/functions/mob/0022.red_knight/tick/2.1.teleport.mcfunction, Asset/data/asset/functions/mob/0022.red_knight/tick/skill_tp_slash/1.skill_tp_slash.mcfunction
ditanceをつければディメンションを跨いだプレイヤーを対象にしなくなる（むしろなんで@pでディメンション跨いでるんだよおら！！！）
=> 🐛 赤い騎士がディメンションをまたぐのを防止

Asset/data/asset/functions/mob/1004.tultaria/tick/1.melee_attack/2.first_tick.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/tick/1.melee_attack/3.slash.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/tick/2.tick.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/tick/5.tereport.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/tick/6.starfury_attack/3.summon.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/tick/6.starfury_attack/5.tag_remove.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/tick/7.star_summon/2.first_tick.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/tick/move/spread_facing.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/tick/move/tereport_center.mcfunction
=> 🐛 トゥルタリアがディメンションを跨いだ動きをしかねないのを修正

Asset/data/asset/functions/mob/0237.lunatic_mage/skill/elemental_confine/1.mcfunction, Asset/data/asset/functions/mob/0237.lunatic_mage/skill/elemental_confine/player_pull.mcfunction
=> 🚸 [MOB0237] 必殺技発動時にプレイヤーをがっちり拘束するように

Asset/data/asset/functions/sacred_treasure/0664.soul_fire_armor/trigger/dis_equip/main.mcfunction, Asset/data/asset/functions/sacred_treasure/0665.soul_fire_armor/trigger/dis_equip/main.mcfunction, Asset/data/asset/functions/sacred_treasure/0667.soul_fire_armor/trigger/dis_equip/main.mcfunction
=> 🐛 魂炎纏のdis_equipのミスを修正

Asset/data/asset/functions/sacred_treasure/0078.self_destruct_order/trigger/3.main.mcfunction
=> 🐛 [神器78]意図しないゴーレムが爆発してしまうのを修正

TheSkyBlessing/data/api/functions/teleporter/set_activation_state/from_id.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/tick/star_init/.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/tick/star_init/summon.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/tick/tp/.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/tick/tp/move.mcfunction
=> :ambulance: テレポーターに関する幾つかの問題を修正

TheSkyBlessing/data/asset_manager/functions/island/dispel/.mcfunction
=> :bug: 移動しながらでも島を解呪できてしまうのを修正

TheSkyBlessing/data/asset_manager/functions/sacred_treasure/_index.d.mcfunction, TheSkyBlessing/data/asset_manager/functions/sacred_treasure/cooldown/.mcfunction, TheSkyBlessing/data/asset_manager/functions/sacred_treasure/cooldown/foreach/construct_msgs_and_revert_lcds.mcfunction, TheSkyBlessing/data/asset_manager/functions/sacred_treasure/cooldown/foreach/decrement.mcfunction, TheSkyBlessing/data/asset_manager/functions/sacred_treasure/cooldown/foreach/store_lcd_bar.mcfunction, TheSkyBlessing/data/asset_manager/functions/sacred_treasure/cooldown/main_bar/.mcfunction, TheSkyBlessing/data/asset_manager/functions/sacred_treasure/cooldown/main_bar/_index.d.mcfunction
=> :zap: クールダウン表示のパフォーマンスを改善する

Asset/data/asset/functions/mob/0282.call_fulstuka/0.load.mcfunction, Asset/data/asset/functions/mob/0282.call_fulstuka/_index.d.mcfunction, Asset/data/asset/functions/mob/0282.call_fulstuka/summon/2.summon.mcfunction, Asset/data/asset/functions/mob/0282.call_fulstuka/tick/1.skill_gun/5.damage.mcfunction, Asset/data/asset/functions/mob/0282.call_fulstuka/tick/2.skill_melee/3.slash.mcfunction
=> 🐛 フルストゥーカのmodifierがプレイヤーのmodifierでない問題を修正

TheSkyBlessing/data/asset_manager/functions/sacred_treasure/triggers/use_item/.mcfunction
=> :bug: 特定の条件で食べ物神器が消失するのを修正

TheSkyBlessing/data/lib/functions/damage/core/calc/.mcfunction
=> :bug: 意図しない部分でダメージ計算式がバニラのものと異なっているのを修正

TheSkyBlessing/data/lib/functions/damage/core/health_subtract/non-player.mcfunction
=> :bug: lib:damage/のみで敵を倒したときにonKilledトリガーが発動しないのを修正

TheSkyBlessing/data/player_manager/functions/version_check.mcfunction
=> :arrow_up: Bump to 1.19.X

TheSkyBlessing/data/core/functions/tick/.mcfunction, TheSkyBlessing/data/world_manager/functions/force_difficulty.mcfunction
=> 🚸 難易度をピースフルに出来ない用に

Asset/data/asset/functions/mob/0257.distortion_spellbook/summon/2.summon.mcfunction, Asset/data/asset/functions/mob/0257.distortion_spellbook/tick/2.tick.mcfunction, Asset/data/asset/functions/mob/0258.enemy_teleporter/tick/2.tick.mcfunction, Asset/data/asset/functions/mob/0258.enemy_teleporter/tick/branch.mcfunction, Asset/data/asset/functions/mob/0258.enemy_teleporter/tick/teleport.mcfunction, Asset/data/asset/functions/mob/0258.enemy_teleporter/tick/weak_teleport.mcfunction
HP減少
召喚感覚減らした
魔法陣から引き寄せる範囲減らした
周囲のモブが多い場合、遠くからモブを持ってこないように
=> 🚸 歪みの魔導書をナーフ

TheSkyBlessing/data/asset_manager/functions/teleporter/_index.d.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/update_activation_state/.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/update_activation_state/pop_master_data_from_teleporter_id.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/update_activation_state/try_get_storage_id_from_teleporter.mcfunction
=> :ambulance: 起動状態更新処理に存在しないIDを渡すとデータが壊れるのを修正

TheSkyBlessing/data/world_manager/functions/gimmick/.mcfunction
=> :ambulance: シャード加工機が動作しないのを修正

TheSkyBlessing/data/api/functions/global_vars/get_difficulty.mcfunction, TheSkyBlessing/data/core/functions/_index.d.mcfunction, TheSkyBlessing/data/core/functions/load_once.mcfunction
=> :technologist: 難度値を取得できるAPIを作成

Asset/data/asset/functions/sacred_treasure/0953.meteor_rain/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0953.meteor_rain/trigger/4.emitter_tick.mcfunction, Asset/data/asset/functions/sacred_treasure/0953.meteor_rain/trigger/meteor/5.explosion.mcfunction
=> 【神器0953】メテオレインを強化

TheSkyBlessing/data/api/functions/player_modifier/core/common/update_modifier/.mcfunction, TheSkyBlessing/data/api/functions/player_modifier/core/common/update_modifier/separate_modifiers.mcfunction
=> 🩹 api:player_modifierにてTemporaryがリセットされていなかった問題を修正

TheSkyBlessing/data/api/functions/heal/modifier.mcfunction, TheSkyBlessing/data/lib/functions/heal/.mcfunction, TheSkyBlessing/data/lib/functions/heal/modifier.mcfunction
間違って二つの修正を1コミットでやってしまったのでここに書きます
1. 補正がかからない
2. FIxedHealが機能しない
=> 🐛 api: healの問題を修正

TheSkyBlessing/data/lib/functions/damage/.mcfunction
=> 🚑️ lib:damageのミスを修正

Asset/data/asset/functions/sacred_treasure/0703.wizard_hat/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0704.wizard_robe_upper/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0705.wizard_robe_lower/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0706.wizard_boots/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0707.mage_hat/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0708.mage_robe_upper/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0709.mage_robe_lower/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0710.mage_boots/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0950.residue_of_pumpkin/give/2.give.mcfunction
=> 🐛 一部アイテムの説明文の記述ミスの修正

TheSkyBlessing/data/api/functions/sacred_treasure/give/from_id.mcfunction, TheSkyBlessing/data/api/functions/sacred_treasure/give/from_rarity.mcfunction, TheSkyBlessing/data/asset/functions/sacred_treasure/common/give.mcfunction
[![lint-datapack](https://github.com/haiiro2gou/TheSkyBlessing/actions/workflows/datapack-linter.yml/badge.svg?branch=fix%2Fhaiiro_GiveBox)](https://github.com/haiiro2gou/TheSkyBlessing/actions/workflows/datapack-linter.yml)
=> 🐛 box指定時にプレイヤーにも神器がgiveされるバグを修正

Asset/data/asset/functions/sacred_treasure/0383.i_scream_ice_cream/trigger/3.main.mcfunction
=> 🚸 こーりごりのダジャレを二つ追加

Asset/data/asset/functions/sacred_treasure/0920.dal_i_thalion/give/2.give.mcfunction
=> ⚖️ [神器0920] ダル・イ・サリオンのナーフ

TheSkyBlessing/data/api/functions/sacred_treasure/box/from_id.mcfunction, TheSkyBlessing/data/api/functions/sacred_treasure/box/from_rarity.mcfunction, TheSkyBlessing/data/api/functions/sacred_treasure/give/from_id.mcfunction, TheSkyBlessing/data/api/functions/sacred_treasure/give/from_rarity.mcfunction, TheSkyBlessing/data/api/functions/sacred_treasure/spawn/from_id.mcfunction, TheSkyBlessing/data/api/functions/sacred_treasure/spawn/from_rarity.mcfunction, TheSkyBlessing/data/asset/functions/sacred_treasure/common/give.mcfunction
現時点で正常に神器のgiveが実行できないという事態(誤解?)に陥っている原因
発端が自分なのもあって一応一つ変更を提示
正直mcf直呼び出しによるgiveを封じる方向での変更は適切ではないと思う
=> 🐛 神器のgive実行時にTypeがないときに正常に実行されるように

Asset/data/asset/functions/mob/0217.medousa_eye/death/2.death.mcfunction, Asset/data/asset/functions/mob/0228.frost_eye/death/2.death.mcfunction
=> 🥚 一部のアイ系Mobが頭をドロップするように

Asset/data/asset/functions/mob/0084.falcios_priest/tick/2.tick.mcfunction
・スキル間隔を長くする弱体化
・ハードの場合、回復と攻撃を同時に行うように
=> ⚖️ ファルシオスの神官の修正とハード対応

Asset/data/asset/functions/mob/0056.thunder_trifler/attack/2.attack.mcfunction, Asset/data/asset/functions/mob/0056.thunder_trifler/hurt/2.hurt.mcfunction, Asset/data/asset/functions/mob/0056.thunder_trifler/hurt/teleport.mcfunction
=> ⚖️ [Mob56]雷弄者ハード化

Asset/data/asset/functions/sacred_treasure/0844.closed_eyes_of_love/give/2.give.mcfunction
=> 🐛 ST0844 Conditionの構文ミスを修正

Asset/data/asset/functions/sacred_treasure/0249.wakinyan/trigger/3.main.mcfunction
もっといい対処法あるかもしれないけどとりあえず仮対処って感じ
=> 🚸 ワキンヤンの音が大きすぎたのを修正

TheSkyBlessing/data/api/functions/damage/core/calc/resistance.mcfunction
=> :balance_scale: 耐性エフェクトの軽減効果を半減させる

TheSkyBlessing/data/asset_manager/functions/common/context_id/pop.mcfunction, TheSkyBlessing/data/asset_manager/functions/common/context_id/stash.mcfunction, TheSkyBlessing/data/asset_manager/functions/sacred_treasure/give.mcfunction
=> :bug: api:sacred_treasure/*/from_rarityがgive以外動作しないのを修正

Asset/data/asset/functions/sacred_treasure/0107.dispenser_canon/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0210.terra_blade/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0253.holy_barrier/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0295.call_elemental_familiar/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0382.haru_urara/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0573.final_prism/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0801.red_secret_stone/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0822.sound_of_a_star/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0840.honey_bee_stick/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0860.angel_wing/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0898.gale_pendant/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0899.flame_ring/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0905.book_of_metastasis/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0911.reactive_armor_head/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0912.reactive_armor_chest/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0913.reactive_armor_legs/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0914.reactive_armor_feet/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0927.lexiel_s_oath/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0930.z_flag/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0953.meteor_rain/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0966.protection/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0967.enhanced_protection/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0973.call_rod_spirit/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0976.brave_sword/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0986.order_of_healing/give/2.give.mcfunction
=> ♻️ Item に minecraft: 名前空間を付けて統一(#1342 の分割PR)

Asset/data/asset/functions/sacred_treasure/0008.mysterious_tambourine/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0218.iron_storm/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0252.void_transaction/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0277.nudist_carnival/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0365.bloodthirsty_sword/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0431.weather_lock_cane/give/2.give.mcfunction
=> ♻️ 1行で書かれていた AttackInfo を項目毎に分割して定義(#1342 の分割PR)

.github/workflows/datapack-linter.yml
https://github.com/ChenCMD/datapack-linter#%E5%85%A5%E5%8A%9B--inputs
=> 🚨 datapack-linter が AnimatedJava を無視するように

TheSkyBlessing/data/api/functions/mob/core/summon.mcfunction, TheSkyBlessing/data/asset/functions/mob/common/summon.mcfunction
=> :bug: MobAsset v1 で前回の召喚のデータを引き継いでしまうのを修正

Asset/data/asset/functions/trader/0009.building_merchant/register/register.mcfunction
・桜の苗木の取引を追加
・染料の順番をクリエインベントリの順に修正
=> 👽️ 建築商人の修正

TheSkyBlessing/data/api/functions/mob/core/summon.mcfunction, TheSkyBlessing/data/api/functions/mob/summon.mcfunction, TheSkyBlessing/data/asset/functions/mob/common/summon.mcfunction, TheSkyBlessing/data/asset_manager/functions/mob/summon/set_data.mcfunction, TheSkyBlessing/data/minecraft/functions/test.mcfunction
=> :sparkles: MobAsset v2 で Field を召喚時に上書きできるように

.github/workflows/datapack-linter.yml
https://github.com/ChenCMD/datapack-linter#readme
=> :construction_worker: Datapack-Linter を v2 に更新

.vscode/tasks.json
=> :wrench: tasks.json を整理

.github/workflows/datapack-linter.yml
=> 💚 正常に Asset リポジトリにコミットされないのを(再)修正

.github/workflows/datapack-linter.yml
https://github.com/actions-js/push#example-workflow-file
- PATを正しく参照するように
- リポジトリの参照を読み込むように
=> :green_heart: 正常にAssetリポジトリにコミットされないのを修正

Asset/data/asset/functions/artifact/0002.blessing/trigger/2.check_condition.mcfunction
=> :children_crossing: [神器0002] 能力ボーナス未選択時の通知を追加

Asset/data/asset/functions/mob/0079.return_thunder/0.load.mcfunction, Asset/data/asset/functions/mob/0079.return_thunder/summon/1.trigger.mcfunction, Asset/data/asset/functions/mob/0079.return_thunder/summon/2.summon.mcfunction, Asset/data/asset/functions/mob/0079.return_thunder/tick/1.trigger.mcfunction, Asset/data/asset/functions/mob/0079.return_thunder/tick/2.tick.mcfunction, Asset/data/asset/functions/mob/0079.return_thunder/tick/3.thunder.mcfunction, Asset/data/asset/functions/mob/0082.thunder_curtain/0.load.mcfunction, Asset/data/asset/functions/mob/0082.thunder_curtain/_index.d.mcfunction, Asset/data/asset/functions/mob/0082.thunder_curtain/summon/1.trigger.mcfunction, Asset/data/asset/functions/mob/0082.thunder_curtain/summon/2.summon.mcfunction, Asset/data/asset/functions/mob/0082.thunder_curtain/tick/1.trigger.mcfunction, Asset/data/asset/functions/mob/0082.thunder_curtain/tick/2.tick.mcfunction, Asset/data/asset/functions/mob/0082.thunder_curtain/tick/3.thunder1.mcfunction, Asset/data/asset/functions/mob/0082.thunder_curtain/tick/4.thunder2.mcfunction, Asset/data/asset/tags/functions/mob/load.json, Asset/data/asset/tags/functions/mob/summon.json, Asset/data/asset/tags/functions/mob/tick.json
=> Mob79,82のProjectileを元に戻す

.gitignore, .vscode/server-start.sh, .vscode/tasks.json
=> :hammer: サーバー起動用タスクを使いやすく

.vscode/settings.json
=> MobAssetV2のテンプレートを作成

TheSkyBlessing/data/api/functions/damage/core/health_subtract/non-player.mcfunction, TheSkyBlessing/data/asset_manager/advancements/artifact/attack/melee.json, TheSkyBlessing/data/asset_manager/advancements/artifact/attack/projectile.json, TheSkyBlessing/data/asset_manager/advancements/artifact/damage/explode.json, TheSkyBlessing/data/asset_manager/advancements/artifact/damage/fire.json, TheSkyBlessing/data/asset_manager/advancements/artifact/damage/from_entity/melee.json, TheSkyBlessing/data/asset_manager/advancements/artifact/damage/from_entity/projectile.json, TheSkyBlessing/data/asset_manager/advancements/artifact/killed/melee.json, TheSkyBlessing/data/asset_manager/advancements/artifact/killed/projectile.json, TheSkyBlessing/data/asset_manager/functions/mob/summon/set_data.mcfunction
進捗の書き方がダメージタイプが導入されたタイミングで変更されたのでそれに関するバグ修正
=> 進捗のダメージタイプが過去の形式のままであるバグを修正

TheSkyBlessing/data/lib/functions/random/with_biased/is_scarcity_history_included.m.mcfunction, TheSkyBlessing/data/lib/functions/random/with_biased/m.mcfunction, TheSkyBlessing/data/lib/functions/random/with_biased/manual.m.mcfunction, TheSkyBlessing/data/lib/functions/random/with_biased/rec.mcfunction
=> :children_crossing: Random Lib にバイアスをつけれるように

TheSkyBlessing/data/core/functions/load_once.mcfunction, TheSkyBlessing/data/core/functions/tick/player/pre.mcfunction, TheSkyBlessing/data/lib/predicates/in_battle.json, TheSkyBlessing/data/mob_manager/functions/entity_finder/attacked_entity/on_attack.mcfunction, TheSkyBlessing/data/mob_manager/functions/entity_finder/attacking_entity/on_hurt.mcfunction, TheSkyBlessing/data/player_manager/functions/in_battle_tick_score.mcfunction, TheSkyBlessing/data/player_manager/functions/manage_tag/.mcfunction, TheSkyBlessing/data/player_manager/functions/manage_tag/_index.d.mcfunction
=> 戦闘中判定用のPredicateを作成

.editorconfig, .vscode/settings.json
今までのものに関しちゃしょうがないけど、これからは確定させようなってことで
=> :wrench: ファイル末尾の改行を決める

TheSkyBlessing/data/api/functions/damage/.mcfunction, TheSkyBlessing/data/api/functions/damage/core/calc/.mcfunction, TheSkyBlessing/data/api/functions/damage/core/calc/enchantment.mcfunction, TheSkyBlessing/data/api/functions/damage/core/calc/resistance.mcfunction, TheSkyBlessing/data/api/functions/damage/core/health_subtract/.mcfunction, TheSkyBlessing/data/api/functions/damage/core/health_subtract/player.mcfunction, TheSkyBlessing/data/api/functions/damage/core/health_subtract/player/.mcfunction, TheSkyBlessing/data/api/functions/damage/core/health_subtract/player/difficulty_modifier.mcfunction, TheSkyBlessing/data/api/functions/damage/core/trigger_on_damage/.mcfunction
[Discordから](https://discord.com/channels/742465492861845564/743487470162804767/1202266234926940180)
=> :balance_scale: 難易度に応じて被ダメージが変動するように

Asset/data/asset/functions/artifact/0728.magatama_of_soul_eating/give/2.give.mcfunction
=> 🚸 [神器728] 魂喰らいの勾玉のLoreを調整

TheSkyBlessing/data/asset_manager/functions/effect/common/try_pop_effect_data.mcfunction
=> 🐛 エフェクトが同tickに2つ以上付与できない問題を修正

TheSkyBlessing/data/asset_manager/functions/mob/summon/set_tag.mcfunction, TheSkyBlessing/data/mob_manager/functions/_index.d.mcfunction
本来TPしてはならないものに対してTPさせないように移動不可タグを追加しました
=> 移動不可タグ Immovable を追加

TheSkyBlessing/data/lib/functions/array/core/shuffle.mcfunction, TheSkyBlessing/data/lib/functions/array/shuffle.mcfunction
$Index Lib を $Index Temporary に修正することで正常に動作することは確認済み
=> Lib:array/shuffleの修正

TheSkyBlessing/data/api/functions/damage/core/modify_damage.mcfunction
=> ダメージの補正を平均する仕様を破壊

TheSkyBlessing/data/lib/predicates/is_day.json, TheSkyBlessing/data/lib/predicates/is_night.json, TheSkyBlessing/data/lib/predicates/weather/is_raining.json, TheSkyBlessing/data/lib/predicates/weather/is_sunny.json, TheSkyBlessing/data/lib/predicates/weather/is_thundering.json
=> :technologist: 気候・時刻判定にディメンション条件を追加

.github/workflows/datapack-linter.yml, .github/workflows/make-declares-mcf.ts
=> 💚 Asset への自動定義 export が壊れているのを修正

TheSkyBlessing/data/asset/functions/object/call.m.mcfunction
=> Object Asset システムのwithinを修正

TheSkyBlessing/data/api/functions/damage/core/modify/non-player_manual.mcfunction, TheSkyBlessing/data/api/functions/damage/modifier_manual.mcfunction
これがあると ObjectAsset とかでわざわざ entity を特定せずにダメージを与える事ができる
=> :technologist: api:damage/modifier_manual を実装

.vscode/settings.json, TheSkyBlessing/data/api/functions/object/core/summon.mcfunction, TheSkyBlessing/data/asset/functions/object/alias/65534/init.mcfunction, TheSkyBlessing/data/asset/functions/object/alias/65534/register.mcfunction, TheSkyBlessing/data/asset/functions/object/example.1/init/.mcfunction, TheSkyBlessing/data/asset/functions/object/super.init.mcfunction, TheSkyBlessing/data/asset_manager/functions/object/init/.mcfunction, TheSkyBlessing/data/asset_manager/functions/object/init/call_super_method.mcfunction, TheSkyBlessing/data/asset_manager/functions/object/init/init.m.mcfunction, TheSkyBlessing/data/asset_manager/functions/object/summon/init.mcfunction
=> ObjectAssetでInit処理を作れるようになった

TheSkyBlessing/data/asset_manager/functions/mob/triggers/.mcfunction, TheSkyBlessing/data/asset_manager/functions/object/triggers/tick.mcfunction
Oh_My_Dat IDが残り続けないように応急処置を施しました。
=> Oh_My_Dat IDが残らないよう、応急処置を施す

TheSkyBlessing/data/asset_manager/functions/mob/triggers/.mcfunction, TheSkyBlessing/data/asset_manager/functions/object/triggers/tick.mcfunction
=> スコアがある時にフィールドを戻すように修正

TheSkyBlessing/data/lib/functions/rotatable_dxyz/core/each_minus.mcfunction
=> :adhesive_bandage: rotatable_dxyzライブラリのリソース定義を修正

TheSkyBlessing/data/api/functions/heal/.mcfunction, TheSkyBlessing/data/api/functions/heal/reset.mcfunction, TheSkyBlessing/data/lib/functions/score_to_health_wrapper/fluctuation.mcfunction
=> HealAPIにArgument.DisableLogを追加

TheSkyBlessing/data/asset_manager/functions/artifact/_index.d.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/triggers/.mcfunction, TheSkyBlessing/data/core/functions/handler/rejoin.mcfunction
=> Assetのrejoin処理を呼び出す位置を変更

TheSkyBlessing/data/core/functions/load_once.mcfunction, TheSkyBlessing/data/rom/functions/_index.d.mcfunction
=> Romの初期化処理をOMDに倣ったものに変更した

TheSkyBlessing/data/asset_manager/functions/object/summon/register.m.mcfunction
オブジェクトアセットに残っていたデバッグコメントを削除しました。
=> デバックコメントの削除

TheSkyBlessing/data/asset_manager/functions/object/_index.d.mcfunction
=> Object Assetのアクセス修飾子を修正

TheSkyBlessing/data/asset_manager/functions/object/summon/init.mcfunction
=> ObjectAssetにて、Init処理内でkillしたり新しいObject召喚したりしても問題ないようになった

TheSkyBlessing/data/api/functions/entity/player/get_health_per.mcfunction, TheSkyBlessing/data/player_manager/functions/health/regen/do.mcfunction
=> プレイヤー体力割合取得APIの計算倍率がおかしいのを修正

TheSkyBlessing/data/api/functions/entity/player/get_health_per.mcfunction, TheSkyBlessing/data/asset_manager/functions/mob/common_tag/anti_void_action/damage.mcfunction, TheSkyBlessing/data/player_manager/functions/fall_damage/deal_damage/get_vars.mcfunction, TheSkyBlessing/data/player_manager/functions/set_team_and_per_health.mcfunction
=> プレイヤーの最大体力取得処理をAPIで行うように変更

TheSkyBlessing/data/asset_manager/functions/mob/common_tag/.mcfunction
=> 🩹 AntiVoid判定のy座標を-64まで下げる

.vscode/settings.json, TheSkyBlessing/data/asset_manager/functions/object/call_method/run_method.m.mcfunction, TheSkyBlessing/data/asset_manager/functions/object/init/init.m.mcfunction, TheSkyBlessing/data/asset_manager/functions/object/summon/summon.m.mcfunction, TheSkyBlessing/data/asset_manager/functions/object/tick/tick.m.mcfunction
・これにより、いちいち実装フラグ立てなくてもよくなるはずです
・ただ、MobAssetV3のほうのテンプレートの変更がかち合う可能性があるのでマージの際は注意が必要かも
・あとこれまたAssetにはテンプレの変更だけのプルリクが飛ぶんですかね？
=> 🧑‍💻 ObjectAsset で Implement フラグが自動で立つように

TheSkyBlessing/data/api/functions/inventory/core/clear/remove/.mcfunction, TheSkyBlessing/data/api/functions/inventory/core/clear/remove/map.mcfunction, TheSkyBlessing/data/api/functions/inventory/set.mcfunction, TheSkyBlessing/data/player_manager/functions/lost_item/drop/.mcfunction, TheSkyBlessing/data/player_manager/functions/lost_item/regive_soulbound.mcfunction, TheSkyBlessing/data/player_manager/functions/lost_item/take.mcfunction
ついでに無信仰の時に消滅の呪い付きのアイテムが消えないバグも修正してるよ
=> :sparkles: TSB.SoulBound == true であるようなアイテムが死んでも保持されるように

TheSkyBlessing/data/asset_manager/functions/mob/summon/init.mcfunction, TheSkyBlessing/data/asset_manager/functions/mob/summon/set_data.mcfunction
=> :bug: MobAsset v3 の init タイミングが v2 と違うのを修正

TheSkyBlessing/data/api/functions/damage/.mcfunction, TheSkyBlessing/data/api/functions/damage/core/health_subtract/player/.mcfunction, TheSkyBlessing/data/api/functions/damage/core/reset.mcfunction, TheSkyBlessing/data/player_manager/functions/fall_damage/deal_damage/.mcfunction, TheSkyBlessing/data/player_manager/functions/fall_damage/deal_damage/deal.mcfunction
=> :children_crossing: 落下ダメージ関連の仕様を調整

TheSkyBlessing/data/asset_manager/functions/artifact/triggers/damage/foreach.mcfunction
=> :ambulance: attack トリガーが damage を受けた時に発動するのを修正

TheSkyBlessing/data/asset_manager/functions/mob/common_tag/.mcfunction
=> :adhesive_bandage: 問答無用でMobが地上へ帰還しようとするのを修正

TheSkyBlessing/data/api/functions/damage/core/trigger_events/non-player/attack_and_hurt/push_from_attacker.mcfunction, TheSkyBlessing/data/api/functions/damage/core/trigger_events/non-player/kill_and_death/push_from_attacker.mcfunction, TheSkyBlessing/data/api/functions/damage/core/trigger_events/player/attack_and_damage/push_from_attacker.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/_index.d.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/triggers/.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/triggers/attack/foreach.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/triggers/damage/foreach.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/triggers/killed/foreach.mcfunction, TheSkyBlessing/data/mob_manager/functions/entity_finder/entity_hurt_player/fetch_entity.mcfunction, TheSkyBlessing/data/mob_manager/functions/entity_finder/player_hurt_entity/fetch_entity.mcfunction
=> :bug: API 経由のトリガーで攻撃先/攻撃元を特定出来ないのを修正

TheSkyBlessing/data/asset_manager/functions/effect/tick.mcfunction
=> :technologist: EffectAssetの処理順を明確化

TheSkyBlessing/data/lib/functions/array/_index.d.mcfunction, TheSkyBlessing/data/lib/functions/array/core/math/max.mcfunction, TheSkyBlessing/data/lib/functions/array/core/math/min.mcfunction, TheSkyBlessing/data/lib/functions/array/core/math/sum.mcfunction, TheSkyBlessing/data/lib/functions/array/math/max.mcfunction, TheSkyBlessing/data/lib/functions/array/math/min.mcfunction, TheSkyBlessing/data/lib/functions/array/math/sum.mcfunction
- (多分) `lib:array/math/sum` のパフォーマンス改善
- `lib:array/math/max` の追加
- `lib:array/math/min` の追加
=> :technologist: lib:array/math/ の改善

TheSkyBlessing/data/asset/functions/artifact/example/trigger/1.trigger.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/cooldown/common/compare_cooldown.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/cooldown/mini_bar/choose_max_cds/foreach.mcfunction
=> :bug: メインクールダウンバーが終了時に一瞬で消えるのを修正

TheSkyBlessing/data/asset/functions/spawner/example/.mcfunction, TheSkyBlessing/data/asset/functions/spawner/example/register.mcfunction, TheSkyBlessing/data/asset_manager/functions/mob/_index.d.mcfunction, TheSkyBlessing/data/asset_manager/functions/spawner/_index.d.mcfunction, TheSkyBlessing/data/asset_manager/functions/spawner/register/.mcfunction, TheSkyBlessing/data/asset_manager/functions/spawner/register/set_data.mcfunction, TheSkyBlessing/data/asset_manager/functions/spawner/subtract_hp/.mcfunction, TheSkyBlessing/data/asset_manager/functions/spawner/subtract_hp/break.mcfunction, TheSkyBlessing/data/asset_manager/functions/spawner/subtract_hp/damage.mcfunction, TheSkyBlessing/data/asset_manager/functions/spawner/subtract_hp/subtract.mcfunction, TheSkyBlessing/data/asset_manager/functions/spawner/subtract_hp/vfx/damage.mcfunction, TheSkyBlessing/data/asset_manager/functions/spawner/tick/4_interval.mcfunction, TheSkyBlessing/data/asset_manager/functions/spawner/tick/is_near_player.mcfunction, TheSkyBlessing/data/core/functions/tick/.mcfunction, TheSkyBlessing/data/mob_manager/functions/kill_entity.mcfunction
=> :children_crossing: スポナーの調整

TheSkyBlessing/data/api/functions/damage/.mcfunction, TheSkyBlessing/data/api/functions/damage/core/attack.mcfunction, TheSkyBlessing/data/api/functions/damage/core/attack_to_forward_target/.mcfunction, TheSkyBlessing/data/api/functions/damage/core/attack_to_forward_target/check_initial_attack.m.mcfunction, TheSkyBlessing/data/api/functions/damage/core/reset.mcfunction, TheSkyBlessing/data/api/functions/entity/mob/effect/core/apply_to_forward_target/apply.m.mcfunction, TheSkyBlessing/data/api/functions/entity/mob/effect/core/apply_to_forward_target/check_initial_apply.m.mcfunction, TheSkyBlessing/data/api/functions/entity/mob/effect/core/apply_to_forward_target/only_initial_apply.m.mcfunction, TheSkyBlessing/data/api/functions/entity/mob/effect/core/get/from_id.m.mcfunction, TheSkyBlessing/data/api/functions/entity/mob/effect/core/give.mcfunction, TheSkyBlessing/data/api/functions/entity/mob/effect/core/remove/from_id.mcfunction, TheSkyBlessing/data/api/functions/entity/mob/effect/core/remove/from_level/.mcfunction, TheSkyBlessing/data/api/functions/entity/mob/effect/get/all.mcfunction, TheSkyBlessing/data/api/functions/entity/mob/effect/get/size/all.mcfunction, TheSkyBlessing/data/api/functions/entity/mob/effect/get/size/bad.mcfunction, TheSkyBlessing/data/api/functions/entity/mob/effect/get/size/good.mcfunction, TheSkyBlessing/data/api/functions/entity/mob/effect/give.mcfunction, TheSkyBlessing/data/api/functions/entity/mob/effect/remove/from_id.mcfunction, TheSkyBlessing/data/api/functions/entity/mob/effect/remove/from_level.mcfunction, TheSkyBlessing/data/api/functions/entity/mob/effect/reset.mcfunction, TheSkyBlessing/data/asset/functions/artifact/example/trigger/3.main.mcfunction, TheSkyBlessing/data/core/functions/load_once.mcfunction
=> :sparkles: マルチ entity 天使用の仕組みを作成

TheSkyBlessing/data/asset/functions/container/example/generate.mcfunction, TheSkyBlessing/data/asset/functions/container/example/register.mcfunction, TheSkyBlessing/data/asset_manager/functions/container/_index.d.mcfunction, TheSkyBlessing/data/asset_manager/functions/container/register/.mcfunction, TheSkyBlessing/data/asset_manager/functions/container/register/set_container_block.m.mcfunction, TheSkyBlessing/data/asset_manager/functions/container/register/set_items/.mcfunction, TheSkyBlessing/data/asset_manager/functions/container/register/set_items/item_normalize/.mcfunction, TheSkyBlessing/data/asset_manager/functions/container/register/set_items/item_normalize/from_artifact.mcfunction, TheSkyBlessing/data/asset_manager/functions/container/register/set_items/item_normalize/from_preset.mcfunction
=> :construction: ContainerAsset の設置処理を作成

TheSkyBlessing/data/asset_manager/functions/mob/summon/set_tag.mcfunction, TheSkyBlessing/data/core/functions/define_const.mcfunction, TheSkyBlessing/data/mob_manager/functions/_index.d.mcfunction, TheSkyBlessing/data/mob_manager/functions/init/multiplay_multiplier/angel.mcfunction, TheSkyBlessing/data/mob_manager/functions/init/multiplay_multiplier/normal.mcfunction
=> :balance_scale: 難易度によって敵の最大体力を補正するように

TheSkyBlessing/data/lib/predicates/in_battle.json
=> ⚖️ lib:in_battleがスペクテイターモードで動作するように

TheSkyBlessing/data/asset_manager/functions/artifact/handler/on_damage_without_source.mcfunction, TheSkyBlessing/data/core/functions/load_once.mcfunction, TheSkyBlessing/data/lib/functions/score_to_health_wrapper/fluctuation.mcfunction, TheSkyBlessing/data/mob_manager/functions/entity_finder/entity_hurt_player/fetch_entity.mcfunction
=> :bug: 緩衝体力がある状態でバニラダメージを受けてもHPが減少しない問題を修正

TheSkyBlessing/data/api/functions/damage/core/health_subtract/player/.mcfunction, TheSkyBlessing/data/api/functions/damage/core/modify/non-player.mcfunction, TheSkyBlessing/data/api/functions/damage/core/modify/non-player_manual.mcfunction, TheSkyBlessing/data/api/functions/damage/core/modify/player.mcfunction, TheSkyBlessing/data/api/functions/damage/core/reset.mcfunction, TheSkyBlessing/data/api/functions/damage/modifier.mcfunction, TheSkyBlessing/data/lib/functions/score_to_health_wrapper/core/store_attack_info/.mcfunction, TheSkyBlessing/data/lib/functions/score_to_health_wrapper/core/store_attack_info/player.m.mcfunction, TheSkyBlessing/data/lib/functions/score_to_health_wrapper/fluctuation.mcfunction
=> 🐛 プレイヤーにダメージを与えると属性に関する情報が意図せず消去される問題を修正

TheSkyBlessing/data/core/functions/define_const.mcfunction
=> :ambulance: 正しくない定数を修正

TheSkyBlessing/data/asset_manager/functions/mob/summon/set_data.mcfunction
=> :technologist: MobAsset/register を使いやすくする

TheSkyBlessing/data/lib/functions/score_to_health_wrapper/fluctuation.mcfunction
=> 🩹 ダメージの DisableLog が引き継がれることがあるのを修正 (デグレ)

TheSkyBlessing/data/lib/functions/status_log/show_health.mcfunction, TheSkyBlessing/data/lib/loot_tables/status_log/damage_with_icon.json
`data modify storage global Config.EnableDamageTypeIcon set value true`
=> :sparkles: ダメージの属性を表示する仕組みを実装

TheSkyBlessing/data/asset_manager/functions/mob/summon/set_data.mcfunction, TheSkyBlessing/data/core/functions/load_once.mcfunction, TheSkyBlessing/data/mob_manager/functions/init/.mcfunction, TheSkyBlessing/data/mob_manager/functions/init/set_tag_and_team.mcfunction
もうセレクターは `@e[type=#lib:living,type=!player,tag=!Uninterferable]` で統一すればいいんじゃないんですかね
=> ⏪ Enemyチームを復元

TheSkyBlessing/data/api/functions/damage/_index.d.mcfunction, TheSkyBlessing/data/api/functions/damage/core/health_subtract/non-player/.mcfunction, TheSkyBlessing/data/api/functions/mob/core/deal_dummy_damage.m.mcfunction, TheSkyBlessing/data/api/functions/mob/deal_dummy_damage.mcfunction
Asset とかでそのまま damage コマンドを使われると entity_finder が動くので
=> :technologist: api:mob/deal_dummy_damage を実装

TheSkyBlessing/data/minecraft/loot_tables/blocks/chorus_flower.json, TheSkyBlessing/data/minecraft/loot_tables/blocks/chorus_plant.json
=> コーラスフルーツがルートテーブルから落ちないように

TheSkyBlessing/data/player_manager/functions/health/regen/check.mcfunction
=> 暫定的に自然回復速度を半分に

TheSkyBlessing/data/api/functions/damage/core/mp_heal.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/create/set_lore/.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/create/set_lore/5.mp_heal_when_hit/.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/create/set_lore/5.mp_heal_when_hit/generate.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/use/.mcfunction, TheSkyBlessing/data/asset_manager/loot_tables/artifact/generate_lore/5.mp_heal_when_hit.json
=> 🧑‍💻 攻撃時のMP回復処理を改善

TheSkyBlessing/data/mob_manager/functions/init/multiplay_multiplier/angel.mcfunction, TheSkyBlessing/data/mob_manager/functions/init/multiplay_multiplier/normal.mcfunction
=> Blesslessのヘルス補正を調整

TheSkyBlessing/data/core/functions/define_const.mcfunction
=> 新しいConstを追加

TheSkyBlessing/data/debug/functions/effect/give.m.mcfunction
=> 🩹 デバッグ用エフェクト付与functionでリセットを行うように

TheSkyBlessing/data/api/functions/teleporter/unsafe/register_manual.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/_index.d.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/register/common/append_or_reorder_teleporters.m.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/register/common/calculate_and_insert_color_data.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/register/construct/.mcfunction, TheSkyBlessing/data/minecraft/functions/tests/summon_teleporters/unsafe.mcfunction
=> :poop: `api:teleporter/unsafe/register_manual` を実装

TheSkyBlessing/data/core/functions/handler/first_join.mcfunction
=> :bug: 他人の EntityStorage 内の Name が上書きされてしまうことがあるのを修正

TheSkyBlessing/data/mob_manager/functions/init/multiplay_multiplier/angel.mcfunction, TheSkyBlessing/data/mob_manager/functions/init/multiplay_multiplier/normal.mcfunction
=> :lipstick: 敵最大体力が整数値になるように

TheSkyBlessing/data/api/functions/inventory/clear.mcfunction, TheSkyBlessing/data/api/functions/inventory/core/clear/remove/subtract_values.mcfunction, TheSkyBlessing/data/minecraft/functions/test2.mcfunction
=> :bug: api:inventory/clear が正常に機能しないのを修正

TheSkyBlessing/data/asset_manager/functions/artifact/create/set_data.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/create/set_hide_flags.mcfunction
=> 神器を強制的にUnbreakable:1bに

TheSkyBlessing/data/lib/functions/rotate_display/.mcfunction, TheSkyBlessing/data/lib/functions/rotate_display/core/marker.mcfunction, TheSkyBlessing/data/lib/tags/entity_types/display.json
=> ディスプレイ回転ライブラリ実装

TheSkyBlessing/data/debug/functions/modify_health/add.m.mcfunction, TheSkyBlessing/data/debug/functions/modify_health/remove.mcfunction, TheSkyBlessing/data/debug/functions/world_asset/construct.m.mcfunction, TheSkyBlessing/data/debug/functions/world_asset/force_fetch.m.mcfunction, TheSkyBlessing/data/minecraft/functions/test.mcfunction
=> :technologist: debug 関数を増やす

TheSkyBlessing/data/asset_manager/functions/artifact/cooldown/main_bar/.mcfunction
=> :bug: 一部神器を手に持った時メインクールダウンバーが消えない問題を修正

TheSkyBlessing/data/asset_manager/functions/artifact/triggers/attack/foreach.mcfunction, TheSkyBlessing/data/asset_manager/functions/mob/triggers/.mcfunction, TheSkyBlessing/data/mob_manager/functions/fix_health.mcfunction
=> :bug: Mob の死亡イベントに関する複数の問題を修正

TheSkyBlessing/data/api/functions/entity/mob/effect/remove/from_level.mcfunction, TheSkyBlessing/data/api/functions/entity/mob/effect/reset.mcfunction
・Argument.ClearCountのデフォルト値を2147483647に
・Argument.IsSingleを完全に削除
=> EffectAPIの修正

TheSkyBlessing/data/asset_manager/functions/artifact/create/set_data.mcfunction
=> :technologist: 神器の AttributeModifiers を空の配列で初期化するように

TheSkyBlessing/data/asset_manager/functions/artifact/give/.mcfunction, TheSkyBlessing/data/asset_manager/functions/spawner/spawn/.mcfunction, TheSkyBlessing/data/asset_manager/functions/spawner/spawn/choose_mob_id/.mcfunction, TheSkyBlessing/data/lib/functions/array/core/shuffle.mcfunction, TheSkyBlessing/data/lib/functions/forward_spreader/core/randomizer.mcfunction, TheSkyBlessing/data/lib/functions/message/common/die/fire.mcfunction, TheSkyBlessing/data/lib/functions/message/common/die/magic.mcfunction, TheSkyBlessing/data/lib/functions/message/common/die/physical.mcfunction, TheSkyBlessing/data/lib/functions/message/common/die/thunder.mcfunction, TheSkyBlessing/data/lib/functions/message/common/die/water.mcfunction, TheSkyBlessing/data/lib/functions/random/.mcfunction, TheSkyBlessing/data/lib/functions/random/with_biased/rec.mcfunction, TheSkyBlessing/data/lib/functions/score_to_health_wrapper/core/show_custom_death_message.mcfunction, TheSkyBlessing/data/lib/functions/spread_entity/core/teleport.mcfunction, TheSkyBlessing/data/player_manager/functions/god/mercy/offering/set_next.mcfunction, TheSkyBlessing/data/player_manager/functions/lost_item/give_part/generate_index.mcfunction
Fix #1812 
ついでに$Randomをリセットしてない奴にリセットを追加したりした
=> 🔥 lib:random/ を削除

TheSkyBlessing/data/api/functions/damage/.mcfunction, TheSkyBlessing/data/api/functions/damage/core/health_subtract/non-player/.mcfunction, TheSkyBlessing/data/api/functions/damage/core/health_subtract/player/.mcfunction, TheSkyBlessing/data/api/functions/damage/core/reset.mcfunction, TheSkyBlessing/data/api/functions/damage/core/trigger_events/non-player/kill_and_death/push_from_attacker.mcfunction, TheSkyBlessing/data/api/functions/heal/.mcfunction, TheSkyBlessing/data/api/functions/heal/core/player.mcfunction, TheSkyBlessing/data/api/functions/heal/core/reset.mcfunction
=> :technologist: DamageAPI 及び HealAPI にトリガーフラグを追加

TheSkyBlessing/data/asset_manager/functions/container/register/construct/common/calculate_count_for_multiplayer.mcfunction, TheSkyBlessing/data/asset_manager/functions/container/register/construct/common/calculate_count_with_multiplay_multiplier.mcfunction, TheSkyBlessing/data/asset_manager/functions/container/register/construct/set_items/item_normalize/from_preset.mcfunction, TheSkyBlessing/data/asset_manager/functions/container/register/construct/set_loot_table/.mcfunction, TheSkyBlessing/data/asset_manager/functions/container/register/construct/set_loot_table/manipulate_item_count.mcfunction
=> :sparkles: コンテナ内の一部アイテムにマルチプレイ倍率がかかるように

TheSkyBlessing/data/core/functions/load_once.mcfunction
大ガバ 
使用箇所:
https://github.com/ProjectTSB/TheSkyBlessing/blob/master/TheSkyBlessing/data/api/functions/mob/apply_to_forward_target/with_idempotent.m.mcfunction#L15
=> :bug: `apply_to_forward_target/with_idempotent.m` の IsForwardedOnly が正常に動作しないのを修正

TheSkyBlessing/data/api/functions/entity/player/get_mp_per.mcfunction
=> MP割合取得APIを追加

TheSkyBlessing/data/api/functions/mob/apply_to_forward_target/with_idempotent.m.mcfunction
=> 🐛 ForwardTargetではない対象に対するAPIの実行が正常に動作しない問題を修正

TheSkyBlessing/data/asset/functions/artifact/common/give.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/check/.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/create/set_data.mcfunction
=> :technologist: 神器の条件確認処理を無視できるフラグを追加

TheSkyBlessing/data/world_manager/functions/gimmick/.mcfunction
=> :technologist: 開発環境下で暗所ペナルティに関連する処理を実行しないように

TheSkyBlessing/data/api/functions/artifact/core/from_id.mcfunction, TheSkyBlessing/data/api/functions/artifact/core/from_rarity/.mcfunction, TheSkyBlessing/data/api/functions/artifact/core/from_rarity/foreach.mcfunction
=> 🐛 神器の生成方式が正常に設定できない問題を修正

TheSkyBlessing/data/common/loot_tables/supplies/lv-1.json, TheSkyBlessing/data/common/loot_tables/supplies/lv-2.json, TheSkyBlessing/data/common/loot_tables/supplies/lv-3.json, TheSkyBlessing/data/common/loot_tables/supplies/lv-4.json
Blocked by #1867 
Fix #1896 
---
羊毛とかアリアドネの糸を入れてもいいかも？
=> :sparkles: 小さな浮島用の救援物資ルートテーブルを追加

TheSkyBlessing/data/world_manager/functions/gimmick/darkness/.mcfunction, TheSkyBlessing/data/world_manager/functions/gimmick/darkness/penalty/pick.m.mcfunction
=> 🐛 暗所ペナルティで召喚されるMobの選択処理が正常に行われないことがある問題を修正

TheSkyBlessing/data/world_manager/functions/gimmick/darkness/penalty/pick.m.mcfunction, TheSkyBlessing/data/world_manager/functions/gimmick/darkness/penalty/spawn.mcfunction
=> 🐛 暗所ペナルティでのスポーンが正常に行われない問題を修正

TheSkyBlessing/data/asset_manager/functions/mob/summon/set_data.mcfunction
=> 🐛 Mob召喚時に武器及び防具のattributeを空にできていない問題を修正

TheSkyBlessing/data/asset_manager/functions/spawner/subtract_hp/.mcfunction, TheSkyBlessing/data/asset_manager/functions/spawner/subtract_hp/attempt_subtract.m.mcfunction
=> :balance_scale: 自然湧きした AssetMob がスポナーの耐久を減少させないように

TheSkyBlessing/data/asset_manager/functions/effect/foreach.mcfunction
牛をベースとした AssetMob が作られる可能性を否定しきれないので、削除はしない
=> :bug: 牛乳を飲んだ場合全てのバフ / デバフが削除されうる問題を修正

TheSkyBlessing/data/common/loot_tables/island_rewards/lv-0.json
=> :sparkles: common:island_rewards/lv-0 を実装

TheSkyBlessing/data/api/functions/global_vars/total_islands.mcfunction, TheSkyBlessing/data/core/functions/_index.d.mcfunction, TheSkyBlessing/data/core/functions/handler/join.mcfunction, TheSkyBlessing/data/lib/functions/message/common/dispel_island.mcfunction, TheSkyBlessing/data/player_manager/functions/show_progress.mcfunction, TheSkyBlessing/data/world_manager/functions/area/_index.d.mcfunction
=> :sparkles: ワールド join 時に攻略進捗を表示するように

TheSkyBlessing/data/asset_manager/functions/trader/common/trades_map/.mcfunction, TheSkyBlessing/data/asset_manager/functions/trader/common/trades_map/create_deprecated_item.m.mcfunction
=> :children_crossing: 条件付き交易のしきい値を確認できるように変更

TheSkyBlessing/data/lib/functions/message/god/flora/believe1.mcfunction, TheSkyBlessing/data/lib/functions/message/god/flora/believe2.mcfunction, TheSkyBlessing/data/lib/functions/message/god/flora/mercy.mcfunction, TheSkyBlessing/data/lib/functions/message/god/flora/unbelieve1.mcfunction, TheSkyBlessing/data/lib/functions/message/god/flora/unbelieve2.mcfunction, TheSkyBlessing/data/lib/functions/message/god/nyaptov/believe1.mcfunction, TheSkyBlessing/data/lib/functions/message/god/nyaptov/believe2.mcfunction, TheSkyBlessing/data/lib/functions/message/god/nyaptov/mercy.mcfunction, TheSkyBlessing/data/lib/functions/message/god/nyaptov/unbelieve1.mcfunction, TheSkyBlessing/data/lib/functions/message/god/nyaptov/unbelieve2.mcfunction, TheSkyBlessing/data/lib/functions/message/god/rumor/believe1.mcfunction, TheSkyBlessing/data/lib/functions/message/god/rumor/believe2.mcfunction, TheSkyBlessing/data/lib/functions/message/god/rumor/mercy.mcfunction, TheSkyBlessing/data/lib/functions/message/god/rumor/unbelieve1.mcfunction, TheSkyBlessing/data/lib/functions/message/god/rumor/unbelieve2.mcfunction, TheSkyBlessing/data/lib/functions/message/god/urban/believe1.mcfunction, TheSkyBlessing/data/lib/functions/message/god/urban/believe2.mcfunction, TheSkyBlessing/data/lib/functions/message/god/urban/mercy.mcfunction, TheSkyBlessing/data/lib/functions/message/god/urban/unbelieve1.mcfunction, TheSkyBlessing/data/lib/functions/message/god/urban/unbelieve2.mcfunction, TheSkyBlessing/data/lib/functions/message/god/wi-ki/believe1.mcfunction, TheSkyBlessing/data/lib/functions/message/god/wi-ki/believe2.mcfunction, TheSkyBlessing/data/lib/functions/message/god/wi-ki/mercy.mcfunction, TheSkyBlessing/data/lib/functions/message/god/wi-ki/unbelieve1.mcfunction, TheSkyBlessing/data/lib/functions/message/god/wi-ki/unbelieve2.mcfunction
=> 💫神殿での神様のメッセージに顔グラフィックがついた。

TheSkyBlessing/data/player_manager/functions/show_tips.mcfunction
Fix #1956
まだ動作確認をしてないのでDraftにしておく
=> 🚸 tipsにエンド天候とデバフの強弱についてを追加

TheSkyBlessing/data/asset/functions/object/call.m.mcfunction, TheSkyBlessing/data/asset_manager/functions/object/call_method/.mcfunction, TheSkyBlessing/data/asset_manager/functions/object/call_method/call_super_methods/.mcfunction, TheSkyBlessing/data/asset_manager/functions/object/call_method/call_super_methods/foreach.mcfunction
=> :bug: Mixin で実装エラーがまだ出るのを修正

TheSkyBlessing/data/api/functions/artifact/core/from_rarity/.mcfunction, TheSkyBlessing/data/api/functions/artifact/core/from_rarity/construct_and_set_key.m.mcfunction, TheSkyBlessing/data/api/functions/artifact/give/from_rarity.mcfunction, TheSkyBlessing/data/api/functions/artifact/spawn/from_rarity.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/load.mcfunction, TheSkyBlessing/data/common/loot_tables/sacred_shard/blue/lv-1.json, TheSkyBlessing/data/common/loot_tables/sacred_shard/blue/lv-2.json, TheSkyBlessing/data/common/loot_tables/sacred_shard/blue/lv-3.json, TheSkyBlessing/data/common/loot_tables/sacred_shard/blue/lv-4.json, TheSkyBlessing/data/common/loot_tables/sacred_shard/green/lv-1.json, TheSkyBlessing/data/common/loot_tables/sacred_shard/green/lv-2.json, TheSkyBlessing/data/common/loot_tables/sacred_shard/green/lv-3.json, TheSkyBlessing/data/common/loot_tables/sacred_shard/green/lv-4.json, TheSkyBlessing/data/common/loot_tables/sacred_shard/lv-1.json, TheSkyBlessing/data/common/loot_tables/sacred_shard/lv-3.json, TheSkyBlessing/data/common/loot_tables/sacred_shard/lv-4.json, TheSkyBlessing/data/common/loot_tables/sacred_shard/red/lv-1.json, TheSkyBlessing/data/common/loot_tables/sacred_shard/red/lv-2.json, TheSkyBlessing/data/common/loot_tables/sacred_shard/red/lv-3.json, TheSkyBlessing/data/common/loot_tables/sacred_shard/red/lv-4.json, TheSkyBlessing/data/metric/functions/shard.m.mcfunction, TheSkyBlessing/data/world_manager/functions/gimmick/shard_processor/process/complete.mcfunction
=> :sparkles: カラーシャードを実装

TheSkyBlessing/data/world_manager/functions/area/01-50.training_area/.mcfunction, TheSkyBlessing/data/world_manager/functions/area/01-50.training_area/summon/fragile_dummy.mcfunction, TheSkyBlessing/data/world_manager/functions/area/01-50.training_area/summon/magical_dummy.mcfunction, TheSkyBlessing/data/world_manager/functions/area/01-50.training_area/summon/normal_dummy.mcfunction, TheSkyBlessing/data/world_manager/functions/area/01-50.training_area/summon/physical_dummy.mcfunction, TheSkyBlessing/data/world_manager/functions/area/01.god_boundaries/on_tick.mcfunction, TheSkyBlessing/data/world_manager/predicates/area/01-50.training_area.json
=> ✨️トレーニングエリアを作成

TheSkyBlessing/data/api/functions/artifact/core/from_rarity/.mcfunction
=> :bug: シャード加工機が動作しない問題を修正

TheSkyBlessing/data/api/functions/button/core/create_text_component.m.mcfunction, TheSkyBlessing/data/api/functions/button/create_text_component.mcfunction, TheSkyBlessing/data/api/functions/button/send.mcfunction, TheSkyBlessing/data/core/functions/load_once.mcfunction, TheSkyBlessing/data/core/functions/tick/player/.mcfunction, TheSkyBlessing/data/lib/functions/macro/call.m.mcfunction, TheSkyBlessing/data/lib/functions/macro/run.m.mcfunction, TheSkyBlessing/data/player_manager/functions/trigger/.mcfunction, TheSkyBlessing/data/player_manager/functions/trigger/_index.d.mcfunction, TheSkyBlessing/data/player_manager/functions/trigger/call_listener/.mcfunction, TheSkyBlessing/data/player_manager/functions/trigger/call_listener/call.m.mcfunction, TheSkyBlessing/data/player_manager/functions/trigger/register/find_already_registered_listener.m.mcfunction, TheSkyBlessing/data/player_manager/functions/trigger/register/m.mcfunction
TriggerLinsters にデータが残り続けるのは仕様です。多分大丈夫やろ。
Related #1859
Related #1937
Fix #774
=> :technologist: ButtonAPI を作成

TheSkyBlessing/data/debug/functions/entity_storage/set.m.mcfunction
=> :technologist: debug/entity_storage/set.m を作成

TheSkyBlessing/data/api/functions/button/disable.mcfunction, TheSkyBlessing/data/player_manager/functions/trigger/common/find_already_registered_listener.m.mcfunction, TheSkyBlessing/data/player_manager/functions/trigger/disable/m.mcfunction, TheSkyBlessing/data/player_manager/functions/trigger/disable/remove.m.mcfunction, TheSkyBlessing/data/player_manager/functions/trigger/register/find_already_registered_listener.m.mcfunction, TheSkyBlessing/data/player_manager/functions/trigger/register/get_or_allocate_id.m.mcfunction
=> :bug: api:button/disable がぶち壊れてるのを修正

TheSkyBlessing/data/player_manager/functions/grave/build/.mcfunction, TheSkyBlessing/data/player_manager/functions/grave/build/m.mcfunction, TheSkyBlessing/data/player_manager/functions/grave/build/set_data.mcfunction, TheSkyBlessing/data/player_manager/functions/grave/tick/.mcfunction, TheSkyBlessing/data/player_manager/functions/grave/tick/break.mcfunction, TheSkyBlessing/data/player_manager/functions/grave/tick/check_with_user.mcfunction, TheSkyBlessing/data/player_manager/functions/grave/tick/stop_motion.mcfunction
=> 🚸墓の仕様変更。右クリックで中身を出すようになった。

TheSkyBlessing/data/asset_manager/functions/artifact/handler/on_damage_without_source.mcfunction, TheSkyBlessing/data/lib/functions/score_to_health_wrapper/core/die.mcfunction, TheSkyBlessing/data/lib/functions/score_to_health_wrapper/core/store_attack_info/.mcfunction, TheSkyBlessing/data/lib/functions/score_to_health_wrapper/fluctuation.mcfunction, TheSkyBlessing/data/lib/functions/score_to_health_wrapper/proc.mcfunction
=> :bug: バリアが付与されている状態でバリア以下の環境ダメージを受けないのを修正

TheSkyBlessing/data/lib/functions/distance/as_to_at.mcfunction, TheSkyBlessing/data/lib/functions/distance/core/get_delta.m.mcfunction, TheSkyBlessing/data/lib/functions/distance/core/get_pos.mcfunction, TheSkyBlessing/data/lib/functions/rotate_display/.mcfunction
=> 🩹 汎用マーカーの別ディメンション移動を対策

TheSkyBlessing/data/player_manager/functions/grave/build/process_item.mcfunction, TheSkyBlessing/data/player_manager/functions/grave/take_items.mcfunction, TheSkyBlessing/data/player_manager/functions/grave/tick/.mcfunction, TheSkyBlessing/data/player_manager/functions/grave/tick/break.mcfunction, TheSkyBlessing/data/player_manager/functions/grave/tick/check_with_user.mcfunction, TheSkyBlessing/data/player_manager/functions/grave/tick/stop_motion.mcfunction
=> ✨ 墓を壊した際に墓の中のアイテムをインベントリに直接配置するように変更

TheSkyBlessing/data/core/functions/handler/death.mcfunction, TheSkyBlessing/data/core/functions/load_once.mcfunction, TheSkyBlessing/data/player_manager/functions/grave/build/set_data.mcfunction
=> :bug: 一定の条件で墓が消えないなどの問題が発生するのを修正

TheSkyBlessing/data/api/functions/artifact/core/from_id.mcfunction, TheSkyBlessing/data/api/functions/artifact/core/from_rarity/.mcfunction, TheSkyBlessing/data/api/functions/artifact/core/from_rarity/foreach.mcfunction, TheSkyBlessing/data/asset_manager/functions/container/register/construct/common/get_artifact.m.mcfunction, TheSkyBlessing/data/common/loot_tables/island_rewards/artifact_seed/lv-1.json, TheSkyBlessing/data/common/loot_tables/island_rewards/artifact_seed/lv-2.json, TheSkyBlessing/data/common/loot_tables/island_rewards/artifact_seed/lv-3.json, TheSkyBlessing/data/common/loot_tables/island_rewards/artifact_seed/lv-4.json
=> 🐛 api:artifact/*/from_rarity が Rarity を int 型で指定した場合に正常に機能しない問題を修正

TheSkyBlessing/data/core/functions/load_once.mcfunction, TheSkyBlessing/data/player_manager/functions/god/change_believe/change_process/start.mcfunction, TheSkyBlessing/data/player_manager/functions/god/change_believe/change_process/task.mcfunction, TheSkyBlessing/data/player_manager/functions/god/change_believe/disable_change_believe_confirm_buttons.mcfunction, TheSkyBlessing/data/player_manager/functions/god/change_believe/on_change_believe_cancel.mcfunction, TheSkyBlessing/data/player_manager/functions/god/change_believe/on_change_believe_confirm.mcfunction, TheSkyBlessing/data/player_manager/functions/god/change_believe/send_confirm_button.mcfunction, TheSkyBlessing/data/player_manager/functions/god/common/disable_another_believer_in_temple_buttons.mcfunction, TheSkyBlessing/data/player_manager/functions/god/common/disable_buttons.mcfunction, TheSkyBlessing/data/player_manager/functions/god/common/send_another_believer_in_temple_buttons.mcfunction, TheSkyBlessing/data/player_manager/functions/god/common/send_believer_in_temple_menu.mcfunction, TheSkyBlessing/data/player_manager/functions/god/mercy/on_mercy.mcfunction, TheSkyBlessing/data/settings/functions/change_difficulty/on_change_difficulty.m.mcfunction, TheSkyBlessing/data/settings/functions/change_keep_inventory/disable.mcfunction, TheSkyBlessing/data/settings/functions/change_keep_inventory/enable.mcfunction, TheSkyBlessing/data/settings/functions/damage_type_icon/disable.mcfunction, TheSkyBlessing/data/settings/functions/damage_type_icon/enable.mcfunction, TheSkyBlessing/data/settings/functions/disable_all_buttons.mcfunction, TheSkyBlessing/data/settings/functions/resend_setting_menu/as_schedule.mcfunction, TheSkyBlessing/data/settings/functions/resend_setting_menu/reserve.m.mcfunction, TheSkyBlessing/data/settings/functions/send_setting_menu.mcfunction
=> :bug: 神域 ･ 神殿でのボタンの挙動が全体的に怪しいのを修正

TheSkyBlessing/data/asset_manager/functions/teleporter/append_group.m.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/common/increment_activation_state_version.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/common/update_display_state.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/register/construct/.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/set_activate_state.m.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/tick/angel_protection/disable.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/tick/angel_protection/enable.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/tick/cancel/check.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/tick/get_activation_state.m.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/tick/get_activation_state_version.m.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/tick/global.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/tick/player.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/tick/summon_star/init/.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/tick/summon_star/summon/.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/tick/summon_star/summon/as_marker.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/tick/summon_star/summon/set_data.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/tick/summon_star/summon/tp.m.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/tick/vfx/teleporter/.mcfunction
=> ♻️ テレポーターの tick 処理を大幅に改善

.vscode/server-start.sh
=> :hammer: サーバー起動スクリプトの resource-pack を env_file に切り出すように

TheSkyBlessing/data/common/loot_tables/island_rewards/lv-0.json, TheSkyBlessing/data/common/loot_tables/island_rewards/lv-1.json, TheSkyBlessing/data/common/loot_tables/island_rewards/lv-2.json, TheSkyBlessing/data/common/loot_tables/island_rewards/lv-3.json, TheSkyBlessing/data/common/loot_tables/island_rewards/lv-4.json
=> :balance_scale: 報酬量を調整

TheSkyBlessing/data/core/functions/handler/join.mcfunction
Related ProjectTSB/TSB-Resourcepack#11
=> :children_crossing: リソースパックのバージョンチェック機構を追加

TheSkyBlessing/data/settings/functions/change_difficulty/disable_dismiss_request_button.mcfunction, TheSkyBlessing/data/settings/functions/change_difficulty/end_dismiss_time.mcfunction, TheSkyBlessing/data/settings/functions/change_difficulty/on_dismiss_request.mcfunction
=> :bug: 難易度変更が複数人で却下できるのを修正

TheSkyBlessing/data/core/functions/check_datapack_deficient.mcfunction, TheSkyBlessing/data/core/functions/handler/join.mcfunction, TheSkyBlessing/data/core/functions/load.mcfunction, TheSkyBlessing/data/core/functions/load_once.mcfunction, TheSkyBlessing/data/player_manager/functions/notice_datapack_deficient/.mcfunction, TheSkyBlessing/data/player_manager/functions/notice_datapack_deficient/on_mute_datapack_deficient_notice_button.mcfunction
=> :sparkles: データパック欠損チェックシステムを作成

TheSkyBlessing/data/core/advancements/handler/enter_nether_portal.json, TheSkyBlessing/data/core/functions/define_gamerule.mcfunction, TheSkyBlessing/data/core/functions/handler/enter_nether_portal.mcfunction, TheSkyBlessing/data/core/functions/tick/player/.mcfunction
=> :children_crossing: ネザーポータルをプレイヤーがくぐれないように

TheSkyBlessing/data/lib/predicates/is_deep_void.json, TheSkyBlessing/data/lib/predicates/is_void.json
なんでむしろやってなかったんすか
Fix ProjectTSB/Asset#1428
=> :bug: 奈落判定の下限を削除

TheSkyBlessing/data/minecraft/loot_tables/gameplay/fishing/fish.json
=> :balance_scale: 鱈と鮭の確率を調整

TheSkyBlessing/data/asset_manager/functions/trader/common/trades_map/item_normalize/from_artifact.mcfunction
=> :bug: 商人との取引に神器が使用できない問題を修正

TheSkyBlessing/data/asset_manager/functions/artifact/triggers/equipments/enum/slot.m.mcfunction
=> 🧑‍💻 ``asset_manager:artifact/triggers/equipments/enum/slot.m``のスコープを修正

TheSkyBlessing/data/core/functions/tick/check_item_meta/_index.mcfunction, TheSkyBlessing/data/core/functions/tick/check_item_meta/entity.mcfunction, TheSkyBlessing/data/core/functions/tick/check_item_meta/morph_artifact_seed.mcfunction, TheSkyBlessing/data/lib/loot_tables/artifact_seed.json
=> ✨ loot_tableだけでも神器を出せるように

TheSkyBlessing/data/core/functions/load_once.mcfunction, TheSkyBlessing/data/world_manager/functions/gimmick/.mcfunction, TheSkyBlessing/data/world_manager/functions/gimmick/darkness/.mcfunction, TheSkyBlessing/data/world_manager/functions/gimmick/darkness/_index.d.mcfunction, TheSkyBlessing/data/world_manager/functions/gimmick/darkness/do.mcfunction, TheSkyBlessing/data/world_manager/functions/gimmick/darkness/penalty.m.mcfunction
=> :balance_scale: マルチプレイ時にモブの自然湧き量を改善

TheSkyBlessing/data/asset_manager/functions/artifact/check/.mcfunction
=> 🚸 神器の使用条件を2つ以上満たしていない場合に複数のログが出る問題を修正

TheSkyBlessing/data/api/functions/data_get/_refetch.mcfunction, TheSkyBlessing/data/api/functions/data_get/_restore_or_fetch.mcfunction, TheSkyBlessing/data/api/functions/data_get/invalidate_cache.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/tick/migrate/.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/tick/migrate/collect_need_migrate_artifacts.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/tick/migrate/migration_artifact.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/tick/migrate/replace.m.mcfunction, TheSkyBlessing/data/core/functions/tick/player/pre.mcfunction
=> :sparkles: 神器の動的マイグレーションシステムを作成

TheSkyBlessing/data/api/functions/data_get/_refetch.mcfunction, TheSkyBlessing/data/api/functions/data_get/_restore_or_fetch.mcfunction, TheSkyBlessing/data/api/functions/data_get/invalidate_cache.mcfunction
=> :technologist: api:data_get/invalidate_cache を作成

TheSkyBlessing/data/core/functions/tick/.mcfunction, TheSkyBlessing/data/player_manager/functions/grave/tick/break.mcfunction
=> :bug: 墓を壊すのと同時に死んだ場合にアイテムが帰ってこない問題を修正

TheSkyBlessing/data/asset_manager/functions/common/datapack/update_state/update/.mcfunction, TheSkyBlessing/data/asset_manager/functions/common/datapack/update_state/update/disable.m.mcfunction, TheSkyBlessing/data/asset_manager/functions/common/datapack/update_state/update/enable.m.mcfunction, TheSkyBlessing/data/asset_manager/functions/common/datapack/update_state/update/foreach.mcfunction, TheSkyBlessing/data/asset_manager/functions/common/datapack/update_state/update/get_path/.mcfunction
=> asset_manager:common/datapack/update_state/update/でオブジェクト3001を召喚するようになった

TheSkyBlessing/data/asset_manager/functions/teleporter/tick/angel_protection/disable.mcfunction, TheSkyBlessing/data/asset_manager/functions/teleporter/tick/angel_protection/enable.mcfunction
=> :bug: AngelProtection で止まったテレポーターの色が変わらない問題を修正

TheSkyBlessing/data/asset_manager/functions/container/register/construct/set_container_block.m.mcfunction
=> :bug: 透明化対策のため、コンテナを一度消してから設置するように

TheSkyBlessing/data/asset_manager/functions/trader/common/trades_map/item_normalize/from_artifact.mcfunction
=> :bug: トレーダーから神器をまとめ買いするとエラーが発生することがある問題を修正

TheSkyBlessing/data/asset_manager/functions/trader/common/trades_map/.mcfunction
=> :bug: 商人と神器を必要とする取引ができない問題を修正

TheSkyBlessing/data/asset_manager/functions/trader/common/trades_map/.mcfunction
=> :bug: Re: 商人と神器を必要とする取引ができない問題を修正

TheSkyBlessing/data/core/functions/load_once.mcfunction, TheSkyBlessing/data/core/functions/migration/.mcfunction, TheSkyBlessing/data/core/functions/migration/v1.0.2/.mcfunction
=> :bookmark: v1.0.2

TheSkyBlessing/data/core/functions/migration/v1.0.3/.mcfunction, TheSkyBlessing/data/player_manager/functions/fall_damage/deal_damage/deal.mcfunction
This reverts commit 6c2cf9f5d59492fb7647d6669fab5ab1188c8093.
=> :fire: Reapply ":wastebasket: 落下ダメージのログ取得をしないように"

TheSkyBlessing/data/lib/functions/has_empty_slot/block.mcfunction, TheSkyBlessing/data/lib/loot_tables/has_empty_slot.json
=> 🧑‍💻 lib:has_empty_slot/blockを作成
