ProjectTSB/TheSkyBlessing

Asset/data/asset/functions/sacred_treasure/0012.sketchy_herb/3.main.mcfunction, Asset/data/asset/functions/sacred_treasure/0188.reverse_transcription_magic/2.check_condition.mcfunction, Asset/data/asset/functions/sacred_treasure/0188.reverse_transcription_magic/3.main.mcfunction, Asset/data/asset/functions/sacred_treasure/0610.call_fish/3.2.attack.mcfunction
怪しい葉っぱの無敵
逆転写魔が使えなかった、tellrawがおかしかったのを修正
コールフィッシュが敵を殺した場合に関係ない敵にパーティクルが出る問題を修正
=> こまかい神器のバグの修正

TheSkyBlock/data/asset/functions/mob/common/summon.mcfunction
=> 🩹 Mobの武器ドロップ率の規定値が適用されてないのを修正

Asset/data/asset/functions/sacred_treasure/0250.phoenix/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0250.phoenix/trigger/3.main.mcfunction, Asset/data/asset/functions/sacred_treasure/0369.fire_magic/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0372.water_magic/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0373.ice_sorcery/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0462.456_dice/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0630.ice_leggings/give/2.give.mcfunction
フェニックスが名前と攻撃属性が合わないのを修正
ウォーターマジック、アイスソーサリーのダメージ表記を修正
456ダイス、lore修正
アイスレギンス、防御の部位が違うのを修正
=> 🐛 複数の神器の説明文/ダメージ表記等を修正

Asset/data/asset/functions/sacred_treasure/0397.floor_sublimation_wing/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0397.floor_sublimation_wing/trigger/2.check_condition.mcfunction
非フルブロック上で実行時、実行位置にテレポートしてしまうバグの修正
また、使用回数が想定した使い方では少なすぎると感じたため、修正
=> 🚸 [神器0397] 階層昇華の羽のバグ修正及び使用回数の調整

Asset/data/asset/functions/sacred_treasure/0218.iron_storm/give/2.give.mcfunction, Asset/data/asset/functions/sacred_treasure/0218.iron_storm/trigger/0.load.mcfunction, Asset/data/asset/functions/sacred_treasure/0218.iron_storm/trigger/3.3.blast.mcfunction, Asset/data/asset/functions/sacred_treasure/0218.iron_storm/trigger/3.main.mcfunction, Asset/data/asset/tags/functions/sacred_treasure/load.json
あまりにも性能が低かったので以下の点修正
・消費MPを120にした
・敵モブへのダメージのみ今までの5倍にした
・modifierが乗るようにした
=> 🚸 [神器0218] アイアンストームを上方修正

TheSkyBlessing/data/lib/tags/items/all.json
=> :bug: #lib:allに1.18のアイテムが含まれていないのを修正

Asset/data/asset/functions/sacred_treasure/0005.musket_matchlock/trigger/3.1.2.damage.mcfunction
dxyzの検知範囲のずれ
damage modifierの未適用
プレイヤーが攻撃対象になっていたのを変更
=> 🐛 [神器0005] マスケット銃のバグ修正

TheSkyBlessing/data/asset/functions/sacred_treasure/common/give.mcfunction
=> :children_crossing: インベントリが満タンで落ちた神器に発光をつけ消えなくする

Asset/data/asset/functions/sacred_treasure/0431.weather_lock_cane/trigger/4.weather_effect.mcfunction, Asset/data/asset/functions/sacred_treasure/0907.rod_of_rain/trigger/rain_cloud/04.effect.mcfunction, Asset/data/asset/functions/sacred_treasure/0930.z_flag/trigger/3.main.mcfunction, Asset/data/asset/functions/sacred_treasure/0952.lunatic_rod/trigger/3.main.mcfunction
大体の防具は既にbaseだったし、大体のバフ系は既にmultiplyでした。
あんまりなおすところなかった。
=> 🚸 神器の属性補正のOperationに一貫性を

Asset/data/asset/functions/sacred_treasure/0898.gale_pendant/register.mcfunction, Asset/data/asset/functions/sacred_treasure/0960.heavy_charm/register.mcfunction, Asset/data/asset/functions/sacred_treasure/0960.heavy_charm/trigger/3.main.mcfunction, Asset/data/asset/functions/sacred_treasure/0960.heavy_charm/trigger/add_modifier.mcfunction, Asset/data/asset/functions/sacred_treasure/0960.heavy_charm/trigger/dis_equip/main.mcfunction, Asset/data/asset/functions/sacred_treasure/0961.light_charm/register.mcfunction, Asset/data/asset/functions/sacred_treasure/0961.light_charm/trigger/3.main.mcfunction, Asset/data/asset/functions/sacred_treasure/0961.light_charm/trigger/add_modifier.mcfunction, Asset/data/asset/functions/sacred_treasure/0961.light_charm/trigger/dis_equip/main.mcfunction, Asset/data/asset/tags/functions/sacred_treasure/register.json
・疾風のペンダントはランク3行き
・軽装、重装チャームの速度上昇、減少が更にデカく
・軽装、重装チャームにそもそもレアリティ設定されてなかったので設定
=> 🚸 [神器0898,0960-0961] 速さに関連する神器を調整

Asset/data/asset/functions/sacred_treasure/0233.reversal/trigger/set_mp.mcfunction
計算時の取得スコアが間違っていました。
作っていた時はHP30%を取得する処理で精一杯でした
=> 🐛 [神器0233] 大逆転が動作しない問題を修正

TheSkyBlessing/data/core/functions/load_once.mcfunction
=> 🐛 信仰アイコンの右に妙な空白がいるのを修正

Asset/data/asset/functions/sacred_treasure/0976.brave_sword/give/2.give.mcfunction
=> 🚸 [神器0976] ブレイブソードのMPコストを調整

Asset/data/asset/functions/mob/0287.burning_stomper/tick/event/stomp.mcfunction, Asset/data/asset/functions/mob/0292.trample_bot/tick/event/stomp.mcfunction
api取得してないせいでダメージ与えられてない問題の修正でもあります。
どういうわけかデバッグ環境ではapiが残ったままだったので気づけなかったようです。
=> ⚖️ ストンパー系モブが無敵時間無視の踏みつけを繰り出すように

TheSkyBlessing/data/mob_manager/functions/entity_finder/attacked_entity/on_attack.mcfunction, TheSkyBlessing/data/mob_manager/functions/entity_finder/attacking_entity/on_hurt.mcfunction
おまけで軽量化Commitが混ざってます
後動作テストはreviewerに任せた
Fix #1115, Fix #1108
=> 🐛 LibraryDamageタグが削除されないのを修正

TheSkyBlessing/data/api/functions/player_modifier/core/attack/base/remove.mcfunction, TheSkyBlessing/data/api/functions/player_modifier/core/attack/fire/remove.mcfunction, TheSkyBlessing/data/api/functions/player_modifier/core/attack/magic/remove.mcfunction, TheSkyBlessing/data/api/functions/player_modifier/core/attack/physical/remove.mcfunction, TheSkyBlessing/data/api/functions/player_modifier/core/attack/thunder/remove.mcfunction, TheSkyBlessing/data/api/functions/player_modifier/core/attack/water/remove.mcfunction, TheSkyBlessing/data/api/functions/player_modifier/core/defense/base/remove.mcfunction, TheSkyBlessing/data/api/functions/player_modifier/core/defense/fire/remove.mcfunction, TheSkyBlessing/data/api/functions/player_modifier/core/defense/magic/remove.mcfunction, TheSkyBlessing/data/api/functions/player_modifier/core/defense/physical/remove.mcfunction, TheSkyBlessing/data/api/functions/player_modifier/core/defense/thunder/remove.mcfunction, TheSkyBlessing/data/api/functions/player_modifier/core/defense/water/remove.mcfunction, TheSkyBlessing/data/api/functions/player_modifier/core/heal/remove.mcfunction, TheSkyBlessing/data/api/functions/player_modifier/core/mp_regen/remove.mcfunction
引数のUUIDに該当するModifierが無いときに前の値を返すバグ
=> :bug: player_modifier/*/removeが間違った値を返すことがあるのを修正

TheSkyBlessing/data/core/functions/load_once.mcfunction, TheSkyBlessing/data/core/functions/migration/v0.1.4/.mcfunction
エンドゲート、チャンクが読み込まれてからクライアント側が飛ぶのでめっちゃラグく見えてめっちゃ気になった
=> :children_crossing: テレポーター以外の各種テレポート先をforceloadする

TheSkyBlessing/data/api/functions/damage/core/trigger_on_attack.mcfunction, TheSkyBlessing/data/api/functions/damage/core/trigger_on_damage/as_attacker.mcfunction, TheSkyBlessing/data/mob_manager/functions/entity_finder/attacked_entity/_index.d.mcfunction, TheSkyBlessing/data/mob_manager/functions/entity_finder/attacked_entity/fetch_attacked_entity.mcfunction, TheSkyBlessing/data/mob_manager/functions/entity_finder/attacking_entity/_index.d.mcfunction, TheSkyBlessing/data/mob_manager/functions/entity_finder/attacking_entity/fetch_attacking_entity.mcfunction, TheSkyBlessing/data/mob_manager/functions/entity_finder/attacking_entity/on_hurt.mcfunction
AttckerFromLibraryじゃなくてAttackerFromLibraryに語字修正するべきなんだけどこのプルリクで修正するか悩んでます
追記：advancementの実行のほうが早いのでadvancementからタグ消すことが出来ません。そういう意図の修正です
=> 🐛 ダメージ対象判定用タグが消えない問題を修正

TheSkyBlessing/data/api/functions/heal/.mcfunction, TheSkyBlessing/data/api/functions/heal/core/modifier.mcfunction, TheSkyBlessing/data/api/functions/heal/core/non-player.mcfunction, TheSkyBlessing/data/api/functions/heal/core/player.mcfunction, TheSkyBlessing/data/api/functions/heal/modifier.mcfunction, TheSkyBlessing/data/api/functions/heal/reset.mcfunction, TheSkyBlessing/data/lib/functions/heal/.mcfunction, TheSkyBlessing/data/lib/functions/heal/modifier.mcfunction, TheSkyBlessing/data/lib/functions/heal/reset.mcfunction, TheSkyBlessing/data/lib/functions/status_log/show_health.mcfunction
`lib:heal/*`はDeprecatedに指定、v0.2.Xの開発を終えた時点で削除します。
Related #1215
=> :truck: HealAPIをlib:からapi:に移動する

Asset/data/asset/functions/mob/0210.aurora_eye/player_process/03.mp_reduction.mcfunction
=> オーロラアイのstorage指定ミスを修正

TheSkyBlessing/data/api/functions/damage/core/health_subtract/player.mcfunction
何故かapi: Argument.DeathMessageを削除してからやっていたのが原因
それに加え
api: Argument.DeathMessage から
api: Argument.DeathMessage に代入するということも行っていたのでそれも削除
=> 🐛 デスログが反映されなかったのを修正

Asset/data/asset/functions/sacred_treasure/0364.red_knights_sword/trigger/3.main.mcfunction
[![lint-datapack](https://github.com/haiiro2gou/TheSkyBlessing/actions/workflows/datapack-linter.yml/badge.svg?branch=fix%2Fhaiiro_364)](https://github.com/haiiro2gou/TheSkyBlessing/actions/workflows/datapack-linter.yml)
=> 📝 赤い騎士の剣のコマンドとIMP-Docが一致していないのを修正

TheSkyBlessing/data/asset_manager/functions/mob/common_tag/break_rides.mcfunction
=> 🐛 Mobの乗り物を破壊するTagでチェスト付きボートが破壊されなかったバグを修正

Asset/data/asset/functions/sacred_treasure/0158.mp_extractor/give/2.give.mcfunction
フレーバーテキストに違和を感じたのでST0159と同じ文言に修正。
SpreadSheetを見てみると名前も違ったので修正。
(そもそも0158,0159共にSpreadSheetにあるフレーバーテキストと完全に別物なんだけど、流石にこれはSpreadSheetの方を修正した方が良いんだろうか…？)
=> 🩹 ST0158 NameとLoreを修正

TheSkyBlessing/data/api/functions/damage/core/get_status/get_resistance_lv.mcfunction
耐性127を無視するための実装だが、HiddenEffectを0で取得してしまう為耐性が1lv扱いとなってしまう問題を修正
=> 🐛 HiddenEffectが0を取得する問題を修正

.github/workflows/datapack-linter.yml
各ブランチの各イベントで同時に一つしか動きません。
動作途中に新たに push された場合は過去のものがキャンセルされ、新しく動き出します。
=> :construction_worker: ワークフローを並列に動作しないように修正

TheSkyBlessing/data/api/functions/damage/core/get_status/get_resistance_lv.mcfunction
=> 1.20.2環境下にて耐性エフェクトの数値が取れないバグを修正

TheSkyBlessing/data/api/functions/mob/core/summon.mcfunction
デバッグ以外では起こらないバグではある
---
mob召喚のfunctionを直で叩いた後にapi経由で召喚すると`asset:mob Return.Summoned`が消えないため一回召喚に失敗するバグの修正
=> :adhesive_bandage: Return.Summonedを念のため削除する

TheSkyBlessing/data/api/functions/heal/core/player.mcfunction, TheSkyBlessing/data/api/functions/heal/core/receive_modifier.mcfunction
Fixed #1503 
・被回復補正を参照する際の条件のミスを修正
・被回復補正をArgument.HealではなくArgument.Fluctuationに乗算するように
=> HealAPIの修正

TheSkyBlessing/data/asset/functions/object/super.init.mcfunction
スラッシュ１個足りないせいで、実際のAssetリポジトリにてasset:object/super.initが呼び出せていませんでした。
ObjectAsset、どうにも問題だらけで申し訳ありません…
=> ObjectAssetのsuper.initの不備を解決

ScoreToHealth/changes.diff, ScoreToHealth/data/score_to_health/functions/modify_max_health.mcfunction
多分想定されてる最大体力を踏み越えるとロックアウトするのが問題なので
回復量を極小にすることで対応してる
…はず
=> 🚑 ScoreToHealthが体力を固定してしまう問題を修正

TheSkyBlessing/data/api/functions/damage/core/trigger_events/non-player/attack_and_hurt/push_from_attacker.mcfunction, TheSkyBlessing/data/api/functions/damage/core/trigger_events/player/attack_and_damage/push_from_attacker.mcfunction, TheSkyBlessing/data/api/functions/heal/core/push_heal_events/healer.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/triggers/attack/add_tag_each_victim.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/triggers/attack/foreach.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/triggers/heal/add_tag_each_receiver.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/triggers/heal/foreach.mcfunction, TheSkyBlessing/data/asset_manager/functions/mob/triggers/attack/add_tag_each_victim.mcfunction, TheSkyBlessing/data/asset_manager/functions/mob/triggers/attack/foreach.mcfunction, TheSkyBlessing/data/mob_manager/functions/entity_finder/entity_hurt_player/fetch_entity.mcfunction, TheSkyBlessing/data/mob_manager/functions/entity_finder/player_hurt_entity/fetch_entity.mcfunction, TheSkyBlessing/data/mob_manager/functions/entity_finder/player_hurt_entity/make_attack_event_data.mcfunction
- 複数体攻撃/ヒールした際に全ての Amounts が記録され、その最大値が Amount に入るように
- To が失われないように
vanilla attack の範囲攻撃を正しい値にするのは出来るなーとは思ったけど面倒だしまぁ誤差なのでいいかなって感じ。
=> 🧑‍💻 トリガー関連の改善

TheSkyBlessing/data/api/functions/entity/mob/effect/core/give.mcfunction, TheSkyBlessing/data/api/functions/entity/mob/effect/give.mcfunction
=> :sparkles: EffectAPI/give で Operation 系を指定できるように

TheSkyBlessing/data/asset_manager/functions/artifact/_index.d.mcfunction
ホットバー神器がマルチトリガーに対応していなかったため
どのみち正式にマルチトリガーがきたらお役御免だろうけど暫定的な処置として
=> 🚨 storageのwithinを修正

TheSkyBlessing/data/player_manager/functions/grave/take_items.mcfunction
=> 🐛 墓の中身に何も入らないバグを修正

TheSkyBlessing/data/core/functions/_index.d.mcfunction, TheSkyBlessing/data/core/functions/tick/player/.mcfunction
- ワールドに入った際にもタグが付与されているのですが、なぜかこれが消えない問題の修正です。根本的な原因は経てていませんが…
=> 🐛 タグ持ちかつ、RespawnEventが80以降ならリスポーン時のイベントを出すように

TheSkyBlessing/data/core/functions/define_const.mcfunction, TheSkyBlessing/data/core/functions/load_once.mcfunction, TheSkyBlessing/data/lib/functions/random/.mcfunction, TheSkyBlessing/data/lib/functions/random/_index.d.mcfunction
=> :children_crossing: RandomLib の内部実装を random コマンドに変更する

TheSkyBlessing/data/core/functions/handler/first_join.mcfunction, TheSkyBlessing/data/player_manager/functions/grave/tick/break.mcfunction, TheSkyBlessing/data/player_manager/functions/grave/tick/stop_motion.mcfunction
=> :children_crossing: 墓を壊した時にアイテムがばら撒かれないように

TheSkyBlessing/data/api/functions/entity/player/absorption/core/get.m.mcfunction
=> :bug: AbsorptionAPI/get で該当 UUID のデータが取得できない時に前のデータが残ってしまう問題を修正

TheSkyBlessing/data/metric/functions/artifact.m.mcfunction
Artifact.UsedCountに`{神器ID: 使用回数}` の形式で保存
Artifact.Usedのデータが多すぎてRCONで取得できない問題への対応
=> メトリックにArtifact.UsedCountを追加

TheSkyBlessing/data/asset_manager/functions/effect/give/give.mcfunction
Fix #1849 
make_effect_data 内で stack を -1 として取り扱うという手もある
remove 処理が実行されないことで弊害がどれほど生じるか分からないので一旦こうした
=> :bug: 削除した Effect の Stack を re-given 時に参照することがある問題を修正

TheSkyBlessing/data/world_manager/functions/gimmick/darkness/break.mcfunction, TheSkyBlessing/data/world_manager/functions/gimmick/darkness/do.mcfunction, TheSkyBlessing/data/world_manager/functions/gimmick/darkness/is_player_nearby/.mcfunction, TheSkyBlessing/data/world_manager/functions/gimmick/darkness/is_player_nearby/check.m.mcfunction, TheSkyBlessing/data/world_manager/functions/gimmick/darkness/penalty/.mcfunction
他プレイヤーの近くに敵が湧く事象や、島の攻略において死霊が際限なく湧いて妨害を行う事象が発生したため
=> ⚖️ 暗所ペナルティの発動条件の調整

TheSkyBlessing/data/asset/functions/artifact/common/give.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/check/.mcfunction
・DisableMPMessage、DisableCooldownMessageがtrueでも関係なく使用不可メッセージが出る
・リセットの際にDisableFlag**s**になっている
=> 🐛 神器の使用不可メッセージに関する問題を修正

TheSkyBlessing/data/api/functions/damage/core/reset.mcfunction, TheSkyBlessing/data/api/functions/damage/single_damage_session/close.mcfunction, TheSkyBlessing/data/api/functions/damage/single_damage_session/open.mcfunction
=> :sparkles: DamageAPI にシングルダメージセッションの仕組みを作成

TheSkyBlessing/data/asset_manager/functions/artifact/triggers/.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/triggers/dis_equip.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/triggers/equip.mcfunction, TheSkyBlessing/data/player_manager/functions/god/_index.d.mcfunction
Blocked by ProjectTSB/Asset#1142
同 tick 内で equip / dis_equip するためトリガー内の EffectAsset が正常に動作しなくなる
=> :bug: 信仰変更時に equip / dis_equip トリガーが処理されない問題を修正

TheSkyBlessing/data/world_manager/functions/area/01-50.training_area/.mcfunction
Fix #1968  
- 召喚時に人形にタグを付与し、指定座標からの範囲内にそのタグ持ちがいなければ再召喚するようになりました。極論ぶっ飛ばしても問題なくなりました。そもそもぶっ飛ばせないようになっているはずですが。
=> :bug: トレーニングエリアの人形の位置を浮遊エフェクトなどで動かすと、再召喚が行われてしまうのを修正。

TheSkyBlessing/data/player_manager/functions/god/change_believe/send_confirm_button.mcfunction, TheSkyBlessing/data/player_manager/functions/god/common/send_another_believer_in_temple_buttons.mcfunction, TheSkyBlessing/data/player_manager/functions/god/common/send_believer_in_temple_menu.mcfunction, TheSkyBlessing/data/settings/functions/send_open_button.mcfunction, TheSkyBlessing/data/settings/functions/send_setting_menu.mcfunction
=> :children_crossing: 各種ボタンの手前に空行を追加する

TheSkyBlessing/data/api/functions/trader/schedule_recipe_update_check.mcfunction, TheSkyBlessing/data/asset_manager/functions/island/dispel/successful.mcfunction, TheSkyBlessing/data/asset_manager/functions/trader/_index.d.mcfunction
=> :sparkles: トレーダーのレシピ更新チェックを API として切り出す

TheSkyBlessing/pack.mcmeta
1.21でフォルダ名が`advancements`から`advancement`に変わるっぽいです
=> 🔥 MInecraftデフォルトの進捗を無効化

TheSkyBlessing/data/asset_manager/functions/artifact/create/set_lore/cooldown/.mcfunction
=> 🐛 神器の消費アイテムが表示されない問題を修正

TheSkyBlessing/data/core/functions/tick/player/.mcfunction, TheSkyBlessing/data/lib/predicates/in_end_gateway.json
Fix #2027 
やってることはシンプルで、溶岩のチェックの処理と同じ方法でゲートウェイに触れてることを検知して、触れてるようなら落下ダメージの処理をスキップするようにしました。
現状、長距離テレポートで落下ダメージを受けるのってエンドゲートウェイだけなんですかね？報告を見る限り、もっぱら神域や練習場への移動で起こるようなので…通常のテレポーターでも起こるようであれば、これとはまた別の対策が必要ですね。
=> 🐛エンドゲートウェイでの移動時、落下ダメージを受けることがあるのを修正

TheSkyBlessing/data/asset/functions/artifact/example/give/2.give.mcfunction, TheSkyBlessing/data/asset_manager/functions/artifact/create/set_lore/equipment/register.mcfunction, TheSkyBlessing/data/asset_manager/loot_tables/artifact/generate_lore/equipment.json
=> :children_crossing: 神器の ｢装備時効果｣ を ｢セット効果｣ に変えられるように

TheSkyBlessing/data/asset_manager/functions/container/register/construct/set_container_block.m.mcfunction
This reverts commit b1ad7927fd4c35cebfd9a7e94e99aa6b58bd60f2.
なんかこれやったら元々入ってたアイテムがばらまかれるようになった、意味わからん
=> :rewind: Revert ":bug: 透明化対策のため、コンテナを一度消してから設置するように"
